FROM node:22.11
ARG FRESH_BUILD=1
WORKDIR /docs
COPY package*.json ./
RUN npm config set registry https://registry.npmjs.org/
RUN npm cache clean --force
RUN npm ci --legacy-peer-deps --progress=true --loglevel=verbose;
COPY . .
EXPOSE 5174
CMD ["npm", "start"]
