# Generated by Django 5.1.3 on 2025-05-03 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Identity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this object.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the identity."),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("accepted", "Accepted"),
                            ("refinement_complete", "Refinement Complete"),
                        ],
                        default="proposed",
                        help_text="Current state of the identity (proposed, accepted, refinement complete).",
                        max_length=32,
                    ),
                ),
                (
                    "notes",
                    models.JSONField(
                        default=list, help_text="Notes about the identity."
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("passions_and_talents", "Passions and Talents"),
                            ("maker_of_money", "Maker of Money"),
                            ("keeper_of_money", "Keeper of Money"),
                            ("spiritual", "Spiritual"),
                            ("personal_appearance", "Personal Appearance"),
                            ("physical_expression", "Physical Expression"),
                            ("familial_relations", "Familial Relations"),
                            ("romantic_relation", "Romantic Relation"),
                            ("doer_of_things", "Doer of Things"),
                        ],
                        help_text="Category this identity belongs to.",
                        max_length=32,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the identity was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the identity was last updated.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user this identity belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
