# Generated by Django 5.1.5 on 2025-05-11 10:28

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Identity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this object.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="A concise label for the identity (e.g., 'Creative Visionary')",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "affirmation",
                    models.TextField(
                        blank=True,
                        help_text="An 'I am' statement with a brief description",
                        null=True,
                    ),
                ),
                (
                    "visualization",
                    models.TextField(
                        blank=True,
                        help_text="(Added in the visualization stage) A vivid mental image",
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("accepted", "Accepted"),
                            ("refinement_complete", "Refinement Complete"),
                        ],
                        default="proposed",
                        help_text="Current state of the identity (proposed, accepted, refinement complete).",
                        max_length=32,
                    ),
                ),
                (
                    "notes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        help_text="List of notes about the identity.",
                        size=None,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("passions_and_talents", "Passions and Talents"),
                            ("maker_of_money", "Maker of Money"),
                            ("keeper_of_money", "Keeper of Money"),
                            ("spiritual", "Spiritual"),
                            ("personal_appearance", "Personal Appearance"),
                            ("physical_expression", "Physical Expression"),
                            ("familial_relations", "Familial Relations"),
                            ("romantic_relation", "Romantic Relation"),
                            ("doer_of_things", "Doer of Things"),
                        ],
                        help_text="Category this identity belongs to.",
                        max_length=32,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the identity was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the identity was last updated.",
                    ),
                ),
            ],
        ),
    ]
