# Generated by Django 5.1.5 on 2025-05-11 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="identity",
            name="user",
            field=models.ForeignKey(
                help_text="The user this identity belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
