# Generated by Django 5.1.5 on 2025-05-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="identity",
            name="description",
        ),
        migrations.AddField(
            model_name="identity",
            name="affirmation",
            field=models.TextField(
                blank=True,
                help_text="An 'I am' statement with a brief description",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="A concise label for the identity (e.g., 'Creative Visionary')",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="visualization",
            field=models.TextField(
                blank=True,
                help_text="(Added in the visualization stage) A vivid mental image",
                null=True,
            ),
        ),
    ]
