# Generated by Django 5.1.3 on 2025-10-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identities", "0005_alter_identity_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="identity",
            old_name="affirmation",
            new_name="i_am_statement",
        ),
        migrations.AlterField(
            model_name="identity",
            name="category",
            field=models.CharField(
                choices=[
                    ("passions_and_talents", "Passions and Talents"),
                    ("maker_of_money", "Maker of Money"),
                    ("keeper_of_money", "Keeper of Money"),
                    ("spiritual", "Spiritual"),
                    ("personal_appearance", "Personal Appearance"),
                    ("physical_expression", "Physical Expression"),
                    ("familial_relations", "Familial Relations"),
                    ("romantic_relation", "Romantic Relation"),
                    ("doer_of_things", "Doer of Things"),
                    ("review", "Review"),
                ],
                help_text="Category this identity belongs to.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("proposed", "Proposed"),
                    ("accepted", "Accepted"),
                    ("refinement_complete", "Refinement Complete"),
                    ("i_am_complete", "I Am Complete"),
                    ("visualization_complete", "Visualization Complete"),
                ],
                default="proposed",
                help_text="Current state of the identity (proposed, accepted, refinement complete).",
                max_length=32,
                null=True,
            ),
        ),
    ]
