# Generated by Django 5.1.3 on 2025-10-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identities", "0006_rename_affirmation_identity_i_am_statement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="category",
            field=models.CharField(
                choices=[
                    ("passions_and_talents", "Passions and Talents"),
                    ("maker_of_money", "Maker of Money"),
                    ("keeper_of_money", "Keeper of Money"),
                    ("spiritual", "Spiritual"),
                    ("personal_appearance", "Personal Appearance"),
                    ("physical_expression", "Physical Expression"),
                    ("familial_relations", "Familial Relations"),
                    ("romantic_relation", "Romantic Relation"),
                    ("doer_of_things", "Doer of Things"),
                ],
                help_text="Category this identity belongs to.",
                max_length=32,
            ),
        ),
    ]
