# Generated by Django 5.1.3 on 2025-11-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identities", "0009_identity_image_ppoi_alter_identity_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("proposed", "Proposed"),
                    ("accepted", "Accepted"),
                    ("refinement_complete", "Refinement Complete"),
                    ("commitment_complete", "Commitment Complete"),
                    ("i_am_complete", "I Am Complete"),
                    ("visualization_complete", "Visualization Complete"),
                    ("archived", "Archived"),
                ],
                default="proposed",
                help_text="Current state of the identity (proposed, accepted, refinement complete).",
                max_length=32,
                null=True,
            ),
        ),
    ]
