# Generated by Django 5.1.3 on 2026-01-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identities", "0010_alter_identity_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="identity",
            name="clothing",
            field=models.TextField(
                blank=True,
                help_text="What the person is wearing in this identity visualization (e.g., 'linen button-down shirt')",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="mood",
            field=models.TextField(
                blank=True,
                help_text="Emotional state/feeling in this identity visualization (e.g., 'proud and calm')",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="setting",
            field=models.TextField(
                blank=True,
                help_text="Environment/location for this identity visualization (e.g., 'on a hill overlooking the ocean')",
                null=True,
            ),
        ),
    ]
