# Generated by Django 5.1.3 on 2026-01-23 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identities", "0011_identity_clothing_identity_mood_identity_setting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentityImageChat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this object.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "chat_history",
                    models.JSONField(
                        default=list,
                        help_text="Serialized Gemini chat history (list of Content objects as JSON). Includes messages, generated images (base64), and thought signatures.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the chat session was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the chat session was last updated.",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        blank=True,
                        help_text="The identity this chat is generating images for.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="image_chats",
                        to="identities.identity",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user this chat session belongs to. One chat per user.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_image_chat",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Identity Image Chat",
                "verbose_name_plural": "Identity Image Chats",
            },
        ),
    ]
