# Generated by Django 5.1.3 on 2026-06-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0012_identityimagechat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identity',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Identity', 'verbose_name_plural': 'Identities'},
        ),
        migrations.AddField(
            model_name='identity',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='User-controlled display order (ascending). New identities are appended to the end; ties break on created_at.'),
        ),
    ]
