/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyEmailIndexRouteImport } from './routes/verify-email/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password/index'
import { Route as CheckEmailIndexRouteImport } from './routes/check-email/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedStudioIndexRouteImport } from './routes/_authenticated/studio/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedIdentitiesIndexRouteImport } from './routes/_authenticated/identities/index'
import { Route as AuthenticatedIamsIndexRouteImport } from './routes/_authenticated/iams/index'
import { Route as AuthenticatedHelpIndexRouteImport } from './routes/_authenticated/help/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat/index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'
import { Route as AuthenticatedIdentitiesIdentityIdRouteImport } from './routes/_authenticated/identities/$identityId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTestRouteImport } from './routes/_authenticated/admin/test'
import { Route as AuthenticatedAdminPromptsRouteImport } from './routes/_authenticated/admin/prompts'
import { Route as AuthenticatedAdminMeditationsRouteImport } from './routes/_authenticated/admin/meditations'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailIndexRoute = VerifyEmailIndexRouteImport.update({
  id: '/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailIndexRoute = CheckEmailIndexRouteImport.update({
  id: '/check-email/',
  path: '/check-email/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioIndexRoute =
  AuthenticatedStudioIndexRouteImport.update({
    id: '/studio/',
    path: '/studio/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIdentitiesIndexRoute =
  AuthenticatedIdentitiesIndexRouteImport.update({
    id: '/identities/',
    path: '/identities/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIamsIndexRoute = AuthenticatedIamsIndexRouteImport.update({
  id: '/iams/',
  path: '/iams/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpIndexRoute = AuthenticatedHelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIdentitiesIdentityIdRoute =
  AuthenticatedIdentitiesIdentityIdRouteImport.update({
    id: '/identities/$identityId',
    path: '/identities/$identityId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTestRoute = AuthenticatedAdminTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPromptsRoute =
  AuthenticatedAdminPromptsRouteImport.update({
    id: '/prompts',
    path: '/prompts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMeditationsRoute =
  AuthenticatedAdminMeditationsRouteImport.update({
    id: '/meditations',
    path: '/meditations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/check-email': typeof CheckEmailIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/login': typeof LoginIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/signup': typeof SignupIndexRoute
  '/verify-email': typeof VerifyEmailIndexRoute
  '/admin/meditations': typeof AuthenticatedAdminMeditationsRoute
  '/admin/prompts': typeof AuthenticatedAdminPromptsRoute
  '/admin/test': typeof AuthenticatedAdminTestRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/identities/$identityId': typeof AuthenticatedIdentitiesIdentityIdRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/help': typeof AuthenticatedHelpIndexRoute
  '/iams': typeof AuthenticatedIamsIndexRoute
  '/identities': typeof AuthenticatedIdentitiesIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/studio': typeof AuthenticatedStudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/check-email': typeof CheckEmailIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/login': typeof LoginIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/signup': typeof SignupIndexRoute
  '/verify-email': typeof VerifyEmailIndexRoute
  '/admin/meditations': typeof AuthenticatedAdminMeditationsRoute
  '/admin/prompts': typeof AuthenticatedAdminPromptsRoute
  '/admin/test': typeof AuthenticatedAdminTestRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/identities/$identityId': typeof AuthenticatedIdentitiesIdentityIdRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/help': typeof AuthenticatedHelpIndexRoute
  '/iams': typeof AuthenticatedIamsIndexRoute
  '/identities': typeof AuthenticatedIdentitiesIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/studio': typeof AuthenticatedStudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/check-email/': typeof CheckEmailIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/verify-email/': typeof VerifyEmailIndexRoute
  '/_authenticated/admin/meditations': typeof AuthenticatedAdminMeditationsRoute
  '/_authenticated/admin/prompts': typeof AuthenticatedAdminPromptsRoute
  '/_authenticated/admin/test': typeof AuthenticatedAdminTestRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/identities/$identityId': typeof AuthenticatedIdentitiesIdentityIdRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/help/': typeof AuthenticatedHelpIndexRoute
  '/_authenticated/iams/': typeof AuthenticatedIamsIndexRoute
  '/_authenticated/identities/': typeof AuthenticatedIdentitiesIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/studio/': typeof AuthenticatedStudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/invite/$token'
    | '/check-email'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/admin/meditations'
    | '/admin/prompts'
    | '/admin/test'
    | '/admin/users'
    | '/identities/$identityId'
    | '/account'
    | '/chat'
    | '/dashboard'
    | '/help'
    | '/iams'
    | '/identities'
    | '/notifications'
    | '/settings'
    | '/studio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/invite/$token'
    | '/check-email'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/admin/meditations'
    | '/admin/prompts'
    | '/admin/test'
    | '/admin/users'
    | '/identities/$identityId'
    | '/account'
    | '/chat'
    | '/dashboard'
    | '/help'
    | '/iams'
    | '/identities'
    | '/notifications'
    | '/settings'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/admin'
    | '/invite/$token'
    | '/check-email/'
    | '/forgot-password/'
    | '/login/'
    | '/onboarding/'
    | '/reset-password/'
    | '/signup/'
    | '/verify-email/'
    | '/_authenticated/admin/meditations'
    | '/_authenticated/admin/prompts'
    | '/_authenticated/admin/test'
    | '/_authenticated/admin/users'
    | '/_authenticated/identities/$identityId'
    | '/_authenticated/account/'
    | '/_authenticated/chat/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/help/'
    | '/_authenticated/iams/'
    | '/_authenticated/identities/'
    | '/_authenticated/notifications/'
    | '/_authenticated/settings/'
    | '/_authenticated/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRoute
  InviteTokenRoute: typeof InviteTokenRoute
  CheckEmailIndexRoute: typeof CheckEmailIndexRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  VerifyEmailIndexRoute: typeof VerifyEmailIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/': {
      id: '/verify-email/'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email/': {
      id: '/check-email/'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/': {
      id: '/_authenticated/studio/'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/identities/': {
      id: '/_authenticated/identities/'
      path: '/identities'
      fullPath: '/identities'
      preLoaderRoute: typeof AuthenticatedIdentitiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/iams/': {
      id: '/_authenticated/iams/'
      path: '/iams'
      fullPath: '/iams'
      preLoaderRoute: typeof AuthenticatedIamsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help/': {
      id: '/_authenticated/help/'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/identities/$identityId': {
      id: '/_authenticated/identities/$identityId'
      path: '/identities/$identityId'
      fullPath: '/identities/$identityId'
      preLoaderRoute: typeof AuthenticatedIdentitiesIdentityIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/test': {
      id: '/_authenticated/admin/test'
      path: '/test'
      fullPath: '/admin/test'
      preLoaderRoute: typeof AuthenticatedAdminTestRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/prompts': {
      id: '/_authenticated/admin/prompts'
      path: '/prompts'
      fullPath: '/admin/prompts'
      preLoaderRoute: typeof AuthenticatedAdminPromptsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/meditations': {
      id: '/_authenticated/admin/meditations'
      path: '/meditations'
      fullPath: '/admin/meditations'
      preLoaderRoute: typeof AuthenticatedAdminMeditationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminMeditationsRoute: typeof AuthenticatedAdminMeditationsRoute
  AuthenticatedAdminPromptsRoute: typeof AuthenticatedAdminPromptsRoute
  AuthenticatedAdminTestRoute: typeof AuthenticatedAdminTestRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminMeditationsRoute: AuthenticatedAdminMeditationsRoute,
    AuthenticatedAdminPromptsRoute: AuthenticatedAdminPromptsRoute,
    AuthenticatedAdminTestRoute: AuthenticatedAdminTestRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedIdentitiesIdentityIdRoute: typeof AuthenticatedIdentitiesIdentityIdRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedHelpIndexRoute: typeof AuthenticatedHelpIndexRoute
  AuthenticatedIamsIndexRoute: typeof AuthenticatedIamsIndexRoute
  AuthenticatedIdentitiesIndexRoute: typeof AuthenticatedIdentitiesIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedStudioIndexRoute: typeof AuthenticatedStudioIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedIdentitiesIdentityIdRoute:
    AuthenticatedIdentitiesIdentityIdRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedHelpIndexRoute: AuthenticatedHelpIndexRoute,
  AuthenticatedIamsIndexRoute: AuthenticatedIamsIndexRoute,
  AuthenticatedIdentitiesIndexRoute: AuthenticatedIdentitiesIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedStudioIndexRoute: AuthenticatedStudioIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRoute,
  InviteTokenRoute: InviteTokenRoute,
  CheckEmailIndexRoute: CheckEmailIndexRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  VerifyEmailIndexRoute: VerifyEmailIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
