# Generated by Django 5.1.3 on 2025-08-03 16:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_messages', '0003_chatmessage_test_scenario'),
        ('test_scenario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this action.', primary_key=True, serialize=False, unique=True)),
                ('action_type', models.CharField(choices=[('create_identity', 'Create Identity'), ('update_identity', 'Update Identity'), ('accept_identity', 'Accept Identity'), ('accept_identity_refinement', 'Accept Identity Refinement'), ('add_identity_note', 'Add Identity Note'), ('transition_phase', 'Transition Phase'), ('select_identity_focus', 'Select Identity Focus'), ('skip_identity_category', 'Skip Identity Category'), ('unskip_identity_category', 'Unskip Identity Category'), ('update_who_you_are', 'Update Who You Are'), ('update_who_you_want_to_be', 'Update Who You Want to Be'), ('add_user_note', 'Add User Note'), ('update_user_note', 'Update User Note'), ('delete_user_note', 'Delete User Note'), ('set_current_identity', 'Set Current Identity')], help_text='Type of action performed by the coach.', max_length=64)),
                ('parameters', models.JSONField(help_text='Parameters passed to the action (stored as JSON).')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action was performed.')),
                ('coach_message', models.ForeignKey(help_text='The coach message that triggered this action.', on_delete=django.db.models.deletion.CASCADE, related_name='triggered_actions', to='chat_messages.chatmessage')),
                ('test_scenario', models.ForeignKey(blank=True, help_text='Test scenario this action is associated with (for test data isolation).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_scenario.testscenario')),
                ('user', models.ForeignKey(help_text='The user this action belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='actions_act_user_id_e96be0_idx'), models.Index(fields=['coach_message'], name='actions_act_coach_m_6679f6_idx'), models.Index(fields=['action_type'], name='actions_act_action__128dd7_idx')],
            },
        ),
    ]
