# Generated by Django 5.1.3 on 2025-11-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_alter_action_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('create_identity', 'Create Identity'), ('create_multiple_identities', 'Create Multiple Identities'), ('update_identity', 'Update Identity'), ('update_identity_name', 'Update Identity Name'), ('update_i_am_statement', 'Update I Am Statement'), ('update_identity_visualization', 'Update Identity Visualization'), ('accept_identity', 'Accept Identity'), ('accept_identity_refinement', 'Accept Identity Refinement'), ('accept_identity_commitment', 'Accept Identity Commitment'), ('accept_i_am_statement', 'Accept I Am Statement'), ('accept_identity_visualization', 'Accept Identity Visualization'), ('add_identity_note', 'Add Identity Note'), ('transition_phase', 'Transition Phase'), ('select_identity_focus', 'Select Identity Focus'), ('skip_identity_category', 'Skip Identity Category'), ('unskip_identity_category', 'Unskip Identity Category'), ('update_who_you_are', 'Update Who You Are'), ('update_who_you_want_to_be', 'Update Who You Want to Be'), ('update_asked_questions', 'Update Asked Questions'), ('set_current_identity', 'Set Current Identity'), ('combine_identities', 'Combine Identities'), ('add_user_note', 'Add User Note'), ('update_user_note', 'Update User Note'), ('delete_user_note', 'Delete User Note'), ('show_introduction_canned_response_component', 'Show Introduction Canned Response Component'), ('show_accept_i_am_component', 'Show Accept I Am Component'), ('show_combine_identities', 'Show Combine Identities'), ('persist_combine_identities', 'Persist Combine Identities')], help_text='Type of action performed by the coach.', max_length=64),
        ),
    ]
