# Generated by Django 5.1.3 on 2026-05-25 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_action_updated_at'),
        ('chat_messages', '0004_chatmessage_component_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('create_identity', 'Create Identity'), ('create_multiple_identities', 'Create Multiple Identities'), ('update_identity', 'Update Identity'), ('update_identity_name', 'Update Identity Name'), ('update_i_am_statement', 'Update I Am Statement'), ('update_identity_visualization', 'Update Identity Visualization'), ('accept_identity', 'Accept Identity'), ('accept_identity_refinement', 'Accept Identity Refinement'), ('accept_identity_commitment', 'Accept Identity Commitment'), ('accept_i_am_statement', 'Accept I Am Statement'), ('accept_identity_visualization', 'Accept Identity Visualization'), ('archive_identity', 'Archive Identity'), ('nest_identity', 'Nest Identity'), ('add_identity_note', 'Add Identity Note'), ('transition_phase', 'Transition Phase'), ('select_identity_focus', 'Select Identity Focus'), ('skip_identity_category', 'Skip Identity Category'), ('unskip_identity_category', 'Unskip Identity Category'), ('update_who_you_are', 'Update Who You Are'), ('update_who_you_want_to_be', 'Update Who You Want to Be'), ('update_asked_questions', 'Update Asked Questions'), ('set_current_identity', 'Set Current Identity'), ('combine_identities', 'Combine Identities'), ('add_user_note', 'Add User Note'), ('update_user_note', 'Update User Note'), ('delete_user_note', 'Delete User Note'), ('show_introduction_canned_response_component', 'Show Introduction Canned Response Component'), ('show_accept_i_am_component', 'Show Accept I Am Component'), ('show_suggest_i_am_statement_component', 'Show Suggest I Am Statement Component'), ('show_i_am_statements_summary_component', 'Show I Am Statements Summary Component'), ('show_combine_identities', 'Show Combine Identities'), ('show_nest_identities', 'Show Nest Identities'), ('show_archive_identity', 'Show Archive Identity'), ('persist_combine_identities', 'Persist Combine Identities'), ('persist_nest_identities', 'Persist Nest Identities'), ('persist_archive_identity', 'Persist Archive Identity'), ('persist_suggest_i_am_statement_component', 'Persist Suggest I Am Statement Component'), ('persist_i_am_statements_summary_component', 'Persist I Am Statements Summary Component'), ('acknowledge_session_video', 'Acknowledge Session Video'), ('start_break', 'Start Break'), ('end_break', 'End Break')], help_text='Type of action performed by the coach.', max_length=64),
        ),
        migrations.AlterField(
            model_name='action',
            name='coach_message',
            field=models.ForeignKey(blank=True, help_text='ChatMessage that triggered this action. Typically the coach message for LLM-emitted actions, or the user message for user-button-driven actions. Nullable for programmatic-only turns (`message=None` in `process_message`, e.g. the video Continue button) where no triggering ChatMessage exists.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_actions', to='chat_messages.chatmessage'),
        ),
        migrations.AlterField(
            model_name='action',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action was first recorded.'),
        ),
    ]
