# Generated by Django 5.1.3 on 2025-07-05 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique name for selecting this test scenario.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description for UI display.')),
                ('template', models.JSONField(help_text='Declarative template describing the initial state for all relevant models.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this scenario (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test Scenario',
                'verbose_name_plural': 'Test Scenarios',
                'ordering': ['-created_at'],
            },
        ),
    ]
