# Generated by Django 5.1.3 on 2025-05-03 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this object.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "current_state",
                    models.CharField(
                        choices=[
                            ("introduction", "Introduction"),
                            ("identity_brainstorming", "Identity Brainstorming"),
                            ("identity_refinement", "Identity Refinement"),
                        ],
                        help_text="Current state of the coaching session.",
                        max_length=32,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional metadata for the coaching session.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the coach state was last updated.",
                    ),
                ),
                (
                    "current_identity",
                    models.ForeignKey(
                        blank=True,
                        help_text="The identity currently being refined.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_coach_states",
                        to="identities.identity",
                    ),
                ),
                (
                    "proposed_identity",
                    models.ForeignKey(
                        blank=True,
                        help_text="The currently proposed identity.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposed_coach_states",
                        to="identities.identity",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user this coach state belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
