# Generated by Django 5.1.5 on 2025-05-11 10:28

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoachState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this object.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "current_state",
                    models.CharField(
                        choices=[
                            ("introduction", "Introduction"),
                            ("identity_brainstorming", "Identity Brainstorming"),
                            ("identity_refinement", "Identity Refinement"),
                        ],
                        help_text="Current state of the coaching session.",
                        max_length=32,
                    ),
                ),
                (
                    "identity_focus",
                    models.CharField(
                        choices=[
                            ("passions_and_talents", "Passions and Talents"),
                            ("maker_of_money", "Maker of Money"),
                            ("keeper_of_money", "Keeper of Money"),
                            ("spiritual", "Spiritual"),
                            ("personal_appearance", "Personal Appearance"),
                            ("physical_expression", "Physical Expression"),
                            ("familial_relations", "Familial Relations"),
                            ("romantic_relation", "Romantic Relation"),
                            ("doer_of_things", "Doer of Things"),
                        ],
                        default="passions_and_talents",
                        help_text="The identity focus for the coaching session.",
                        max_length=255,
                    ),
                ),
                (
                    "goals",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        help_text="List of goals for the coaching session. Postgres only.",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata for the coaching session.",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the coach state was last updated.",
                    ),
                ),
            ],
        ),
    ]
