# Generated by Django 5.1.5 on 2025-05-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coach_states", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachstate",
            name="goals",
            field=models.JSONField(
                default=list, help_text="Goals for the coaching session."
            ),
        ),
    ]
