# Generated by Django 5.1.5 on 2025-05-11 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("coach_states", "0001_initial"),
        ("identities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachstate",
            name="current_identity",
            field=models.ForeignKey(
                blank=True,
                help_text="The identity currently being refined.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_coach_states",
                to="identities.identity",
            ),
        ),
        migrations.AddField(
            model_name="coachstate",
            name="proposed_identity",
            field=models.ForeignKey(
                blank=True,
                help_text="The currently proposed identity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposed_coach_states",
                to="identities.identity",
            ),
        ),
    ]
