# Generated by Django 5.1.5 on 2025-05-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coach_states", "0002_coachstate_goals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coachstate",
            name="goals",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Goals for the coaching session.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="coachstate",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional metadata for the coaching session.",
                null=True,
            ),
        ),
    ]
