# Generated by Django 5.1.5 on 2025-05-15 12:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coach_states", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachstate",
            name="skipped_identity_categories",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("passions_and_talents", "Passions and Talents"),
                        ("maker_of_money", "Maker of Money"),
                        ("keeper_of_money", "Keeper of Money"),
                        ("spiritual", "Spiritual"),
                        ("personal_appearance", "Personal Appearance"),
                        ("physical_expression", "Physical Expression"),
                        ("familial_relations", "Familial Relations"),
                        ("romantic_relation", "Romantic Relation"),
                        ("doer_of_things", "Doer of Things"),
                    ],
                    max_length=64,
                ),
                blank=True,
                default=list,
                help_text="List of identity categories that the user has chosen to skip.",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="coachstate",
            name="current_state",
            field=models.CharField(
                choices=[
                    ("system_context", "System Context"),
                    ("introduction", "Introduction"),
                    ("identity_brainstorming", "Identity Brainstorming"),
                    ("identity_refinement", "Identity Refinement"),
                ],
                help_text="Current state of the coaching session.",
                max_length=32,
            ),
        ),
    ]
