# Generated by Django 5.1.3 on 2025-05-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coach_states", "0003_alter_coachstate_goals_alter_coachstate_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachstate",
            name="identity_focus",
            field=models.CharField(
                choices=[
                    ("passions_and_talents", "Passions and Talents"),
                    ("maker_of_money", "Maker of Money"),
                    ("keeper_of_money", "Keeper of Money"),
                    ("spiritual", "Spiritual"),
                    ("personal_appearance", "Personal Appearance"),
                    ("physical_expression", "Physical Expression"),
                    ("familial_relations", "Familial Relations"),
                    ("romantic_relation", "Romantic Relation"),
                    ("doer_of_things", "Doer of Things"),
                ],
                default="passions_and_talents",
                help_text="The identity focus for the coaching session.",
                max_length=255,
            ),
        ),
    ]
