# Generated by Django 5.1.5 on 2025-05-15 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coach_states", "0004_coachstate_skipped_identity_categories_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coachstate",
            name="goals",
        ),
    ]
