# Generated by Django 5.1.3 on 2025-05-24 18:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coach_states", "0005_remove_coachstate_goals"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachstate",
            name="who_you_are",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="List of 'who you are' identities provided by the user.",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="coachstate",
            name="who_you_want_to_be",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="List of 'who you want to be' identities provided by the user.",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="coachstate",
            name="current_state",
            field=models.CharField(
                choices=[
                    ("system_context", "System Context"),
                    ("introduction", "Introduction"),
                    ("identity_warm_up", "Identity Warm-Up"),
                    ("identity_brainstorming", "Identity Brainstorming"),
                    ("identity_refinement", "Identity Refinement"),
                ],
                help_text="Current state of the coaching session.",
                max_length=32,
            ),
        ),
    ]
