# Generated by Django 5.1.3 on 2025-07-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coach_states", "0007_rename_current_state_coachstate_current_phase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coachstate",
            name="current_phase",
            field=models.CharField(
                choices=[
                    ("system_context", "System Context"),
                    ("introduction", "Introduction"),
                    ("get_to_know_you", "Get to Know You"),
                    ("identity_warm_up", "Identity Warm-Up"),
                    ("identity_brainstorming", "Identity Brainstorming"),
                    ("identity_refinement", "Identity Refinement"),
                ],
                help_text="Current state of the coaching session.",
                max_length=32,
            ),
        ),
    ]
