# Generated by Django 5.1.3 on 2025-08-12 13:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_states', '0010_alter_coachstate_current_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachstate',
            name='asked_questions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='List of questions that have been asked during the Get To Know You phase.', size=None),
        ),
    ]
