# Generated by Django 5.1.3 on 2025-08-12 13:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_states', '0011_coachstate_asked_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachstate',
            name='asked_questions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('background_upbringing', 'Background/upbringing'), ('family_structure', 'Family structure (siblings, parents, children, etc.)'), ('work_living', 'Work or what they do for a living'), ('hobbies_interests', 'Hobbies or interests'), ('why_here_hopes', 'Why are you here? What do you hope to get out of this coaching?')], max_length=255), blank=True, default=list, help_text='List of questions that have been asked during the Get To Know You phase.', size=None),
        ),
    ]
