# Generated by Django 5.1.3 on 2025-10-22 20:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coach_states", "0012_alter_coachstate_asked_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coachstate",
            name="current_phase",
            field=models.CharField(
                choices=[
                    ("system_context", "System Context"),
                    ("introduction", "Introduction"),
                    ("get_to_know_you", "Get to Know You"),
                    ("identity_warm_up", "Identity Warm-Up"),
                    ("identity_brainstorming", "Identity Brainstorming"),
                    ("identity_refinement", "Identity Refinement"),
                    ("i_am_statement", "I Am Statement"),
                    ("identity_visualization", "Identity Visualization"),
                ],
                help_text="Current state of the coaching session.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="coachstate",
            name="identity_focus",
            field=models.CharField(
                choices=[
                    ("passions_and_talents", "Passions and Talents"),
                    ("maker_of_money", "Maker of Money"),
                    ("keeper_of_money", "Keeper of Money"),
                    ("spiritual", "Spiritual"),
                    ("personal_appearance", "Personal Appearance"),
                    ("physical_expression", "Physical Expression"),
                    ("familial_relations", "Familial Relations"),
                    ("romantic_relation", "Romantic Relation"),
                    ("doer_of_things", "Doer of Things"),
                    ("review", "Review"),
                ],
                default="passions_and_talents",
                help_text="The identity category focus for the coaching session. Used when ",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="coachstate",
            name="skipped_identity_categories",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("passions_and_talents", "Passions and Talents"),
                        ("maker_of_money", "Maker of Money"),
                        ("keeper_of_money", "Keeper of Money"),
                        ("spiritual", "Spiritual"),
                        ("personal_appearance", "Personal Appearance"),
                        ("physical_expression", "Physical Expression"),
                        ("familial_relations", "Familial Relations"),
                        ("romantic_relation", "Romantic Relation"),
                        ("doer_of_things", "Doer of Things"),
                        ("review", "Review"),
                    ],
                    max_length=64,
                ),
                blank=True,
                default=list,
                help_text="List of identity categories that the user has chosen to skip.",
                size=None,
            ),
        ),
    ]
