# Generated by Django 5.1.3 on 2026-05-24 15:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_states', '0016_alter_coachstate_current_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachstate',
            name='shown_videos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='List of session video keys the user has acknowledged.', size=None),
        ),
    ]
