# Generated by Django 5.1.3 on 2026-05-24 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0004_chatmessage_component_config'),
        ('coach_states', '0017_coachstate_shown_videos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this break.', primary_key=True, serialize=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the break opened (set on creation).')),
                ('ended_at', models.DateTimeField(blank=True, help_text="Timestamp when the user clicked 'I'm Ready' to end the break. NULL means the user is still on a break.", null=True)),
                ('triggered_by_session', models.CharField(help_text="Session key the user just finished when the break started (e.g., 'brainstorming_session').", max_length=255)),
                ('coach_message', models.ForeignKey(blank=True, help_text='The coach ChatMessage carrying the SESSION_BREAK component that opened this break. Nullable so a break survives chat message deletion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='break_anchors', to='chat_messages.chatmessage')),
                ('user', models.ForeignKey(help_text='The user this break belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
    ]
