# Generated by Django 5.1.3 on 2026-06-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coach_states", "0018_break"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachstate",
            name="studio_access_override",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Super-admin override for Studio access. None = default (phase-based: unlocked at the identity_visualization phase); True = force unlocked; False = force locked.",
                null=True,
            ),
        ),
    ]
