--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8 (Debian 16.8-1.pgdg120+1)
-- Dumped by pg_dump version 16.9 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: dev_coach_database_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO dev_coach_database_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: dev_coach_database_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO dev_coach_database_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: dev_coach_database_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO dev_coach_database_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: dev_coach_database_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO dev_coach_database_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_messages_chatmessage; Type: TABLE; Schema: public; Owner: dev_coach_database_user
--

CREATE TABLE public.chat_messages_chatmessage (
    id uuid NOT NULL,
    role character varying(32) NOT NULL,
    content text NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.chat_messages_chatmessage OWNER TO dev_coach_database_user;

--
-- Name: coach_states_coachstate; Type: TABLE; Schema: public; Owner: dev_coach_database_user
--

CREATE TABLE public.coach_states_coachstate (
    id uuid NOT NULL,
    current_state character varying(32) NOT NULL,
    identity_focus character varying(255) NOT NULL,
    goals character varying(255)[],
    metadata jsonb,
    updated_at timestamp with time zone NOT NULL,
    current_identity_id uuid,
    proposed_identity_id uuid,
    user_id uuid NOT NULL
);


ALTER TABLE public.coach_states_coachstate OWNER TO dev_coach_database_user;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: dev_coach_database_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO dev_coach_database_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: dev_coach_database_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO dev_coach_database_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: dev_coach_database_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO dev_coach_database_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: dev_coach_database_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO dev_coach_database_user;

--
-- Name: identities_identity; Type: TABLE; Schema: public; Owner: dev_coach_database_user
--

CREATE TABLE public.identities_identity (
    id uuid NOT NULL,
    name character varying(255),
    affirmation text,
    visualization text,
    state character varying(32) NOT NULL,
    notes text[] NOT NULL,
    category character varying(32) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.identities_identity OWNER TO dev_coach_database_user;

--
-- Name: prompts_prompt; Type: TABLE; Schema: public; Owner: dev_coach_database_user
--

CREATE TABLE public.prompts_prompt (
    id uuid NOT NULL,
    coach_state character varying(32) NOT NULL,
    version integer NOT NULL,
    name character varying(255),
    description text,
    body text NOT NULL,
    required_context_keys character varying(64)[] NOT NULL,
    allowed_actions character varying(64)[] NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.prompts_prompt OWNER TO dev_coach_database_user;

--
-- Name: users_user; Type: TABLE; Schema: public; Owner: dev_coach_database_user
--

CREATE TABLE public.users_user (
    date_joined timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    email character varying(254) NOT NULL,
    password character varying(128) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    is_superuser boolean NOT NULL,
    verification_token character varying(100) NOT NULL,
    email_verification_sent_at timestamp with time zone,
    last_login timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.users_user OWNER TO dev_coach_database_user;

--
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: dev_coach_database_user
--

CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_user_groups OWNER TO dev_coach_database_user;

--
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: dev_coach_database_user
--

CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_user_permissions OWNER TO dev_coach_database_user;

--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: dev_coach_database_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: dev_coach_database_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: dev_coach_database_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add coach state	6	add_coachstate
22	Can change coach state	6	change_coachstate
23	Can delete coach state	6	delete_coachstate
24	Can view coach state	6	view_coachstate
25	Can add chat message	7	add_chatmessage
26	Can change chat message	7	change_chatmessage
27	Can delete chat message	7	delete_chatmessage
28	Can view chat message	7	view_chatmessage
29	Can add identity	8	add_identity
30	Can change identity	8	change_identity
31	Can delete identity	8	delete_identity
32	Can view identity	8	view_identity
33	Can add prompt	9	add_prompt
34	Can change prompt	9	change_prompt
35	Can delete prompt	9	delete_prompt
36	Can view prompt	9	view_prompt
37	Can add User	10	add_user
38	Can change User	10	change_user
39	Can delete User	10	delete_user
40	Can view User	10	view_user
\.


--
-- Data for Name: chat_messages_chatmessage; Type: TABLE DATA; Schema: public; Owner: dev_coach_database_user
--

COPY public.chat_messages_chatmessage (id, role, content, "timestamp", user_id) FROM stdin;
a482bfef-b372-4615-a2f2-197b7fa6d1e7	coach	# Identity Creation Exercise – Simple Role-Playing Dialog\n\nToday, we're going to do something incredibly powerful.\n\nWe are going to **design your life,** not by forcing actions or setting rigid goals, but by shaping **who you are at your core.**\n\nMost people try to change their lives by **forcing behaviors**—telling themselves, *"I need to work out,"* *"I should eat healthier,"* or *"I have to be more disciplined."* But this approach relies on **willpower**, which fades.\n\nReal transformation doesn't start with action. It starts with **identity.**\n\n💡 Instead of struggling to force yourself to go to the gym, you become **a Warrior who trains daily.**  \n💡 Instead of stressing about money, you become **a Wealth Architect who builds abundance with ease.**  \n💡 Instead of trying to "be more confident," you become **a Confident Icon who radiates self-assurance effortlessly.**\n\nWhen you **define who you are,** action becomes **automatic.**\n\n## Why Identity First? Because It Shapes Everything Downstream.\n\nWe are going to **position you in the world intentionally** by designing an **array of identities** that define:\n✅ **How you show up**  \n✅ **How you move through challenges**  \n✅ **How you build your relationships**  \n✅ **How you experience life itself**\n\nThis process isn't about **external labels or expectations.**  \n✅ **Not your dad's values.**  \n✅ **Not your partner's expectations.**  \n✅ **Not society's definition of success.**  \n\nThis is about **what lights you up inside.**\n\nWhen we find the **right identities for you,** you will **feel it.**\n\n💡 It will give you a **surge of energy**—like a puzzle piece snapping into place in your heart.  \n💡 It will **clarify your choices**—because when you know who you are, the right actions become obvious.  \n💡 It will shift you from **forcing action** to **living in alignment.**\n\n## Bringing the External World Inside: Who Are You in Relationship to Your Life?\n\nInstead of seeing different areas of life—**work, fitness, relationships, wealth, health**—as external buckets that you have to manage, we are flipping the perspective:\n\n💡 **Who are you in relationship to your health?** → A Warrior, a Vitality Seeker, an Athlete.  \n💡 **Who are you in relationship to your wealth?** → A Wealth Architect, an Abundant Creator, a Master Investor.  \n💡 **Who are you in relationships?** → A Devoted Partner, a Magnetic Presence, a Deep Connector.\n\nBy making this shift, we move from **obligation to ownership.**\n\nYour external world no longer dictates your actions—**your identity does.**\n\n## Let's Design Your Identity Blueprint\n\nRight now, we're exploring—so don't get **stuck in semantics.** You might start with a concept, and later, we'll refine it into a **powerful noun that you fully own.**\n\n💡 If something feels **off, we tweak it.**  \n💡 If something feels **flat, we expand it.**  \n💡 If something **sparks something inside you**, we lean into it.\n\nThis process is about finding **the words that make you feel free, powerful, and limitless.**\n\n## Final Thought: The Power of Identity in Daily Life\n\nWhen this process is complete, you will never have to **force** action again. You will wake up and know:\n\n🔥 *"I am a Warrior, so I train."*  \n🔥 *"I am a Wealth Architect, so I manage my money wisely."*  \n🔥 *"I am a Confident Icon, so I carry myself with certainty."*\n\nAnd on the days when you slip? That's okay. You will have this **identity map stored in your technology tool, ready to guide you back on track, any time, any day.**\n\nToday, we take the first step.\n\n🚀 **Are you ready?**\n	2025-05-14 18:05:14.569524+00	48bf7f8e-9b9e-4151-be94-64dbdc25a44c
a47d3055-2df0-4761-8a2f-6cd40ebfdb7c	user	yes	2025-05-14 18:05:19.301498+00	48bf7f8e-9b9e-4151-be94-64dbdc25a44c
4b71c064-e900-44ee-a235-03ce6d59ee01	coach	Fantastic! Let's dive into the exciting process of exploring the identities you inhabit every day. Think about the different roles you play and the ways you see yourself in your daily life. Are you a mother, a writer, a singer, an athlete, an executive, a brother, a husband? What are the identities that resonate with you right now?	2025-05-14 18:05:23.44766+00	48bf7f8e-9b9e-4151-be94-64dbdc25a44c
d40ec4d6-7d33-45bf-bcde-e8f9e75ef96a	user	I am  a girlfriend and fitness nut an entrepreneur an athlete an aspiring mother a writer a chef asocial butterfly	2025-05-14 18:08:00.195817+00	48bf7f8e-9b9e-4151-be94-64dbdc25a44c
ba03298c-9c17-45f1-9b4b-e03c07af9040	coach	Amazing! You've shared a wonderful array of identities that you currently resonate with:\n\n- **Girlfriend**\n- **Fitness Nut**\n- **Entrepreneur**\n- **Athlete**\n- **Aspiring Mother**\n- **Writer**\n- **Chef**\n- **Social Butterfly**\n\nNow, let's explore the identities you aspire to become. What do you want to be in the future? These are things you don't feel you are now but crave for the future. Maybe it's a wife or mother. Maybe it's an entrepreneur or a millionaire. Maybe it's a community or thought leader. What aspirational identities come to mind?	2025-05-14 18:08:03.840932+00	48bf7f8e-9b9e-4151-be94-64dbdc25a44c
0e6492bd-b849-4b68-9946-423729b450eb	user	a millionair for sure	2025-05-14 18:08:35.773251+00	48bf7f8e-9b9e-4151-be94-64dbdc25a44c
ba760b3f-2acc-4b87-a84c-4ac49482d7e6	coach	Amazing! You've shared a wonderful array of identities that you currently resonate with:\n\n- **Girlfriend**\n- **Fitness Nut**\n- **Entrepreneur**\n- **Athlete**\n- **Aspiring Mother**\n- **Writer**\n- **Chef**\n- **Social Butterfly**\n\nNow, let's explore the identities you aspire to become. What do you want to be in the future? These are things you don't feel you are now but crave for the future. Maybe it's a wife or mother. Maybe it's an entrepreneur or a millionaire. Maybe it's a community or thought leader. What aspirational identities come to mind?	2025-05-14 18:08:37.996801+00	48bf7f8e-9b9e-4151-be94-64dbdc25a44c
45df6691-7e43-4cef-bc13-8db6f812b612	coach	# Identity Creation Exercise – Simple Role-Playing Dialog\n\nToday, we're going to do something incredibly powerful.\n\nWe are going to **design your life,** not by forcing actions or setting rigid goals, but by shaping **who you are at your core.**\n\nMost people try to change their lives by **forcing behaviors**—telling themselves, *"I need to work out,"* *"I should eat healthier,"* or *"I have to be more disciplined."* But this approach relies on **willpower**, which fades.\n\nReal transformation doesn't start with action. It starts with **identity.**\n\n💡 Instead of struggling to force yourself to go to the gym, you become **a Warrior who trains daily.**  \n💡 Instead of stressing about money, you become **a Wealth Architect who builds abundance with ease.**  \n💡 Instead of trying to "be more confident," you become **a Confident Icon who radiates self-assurance effortlessly.**\n\nWhen you **define who you are,** action becomes **automatic.**\n\n## Why Identity First? Because It Shapes Everything Downstream.\n\nWe are going to **position you in the world intentionally** by designing an **array of identities** that define:\n✅ **How you show up**  \n✅ **How you move through challenges**  \n✅ **How you build your relationships**  \n✅ **How you experience life itself**\n\nThis process isn't about **external labels or expectations.**  \n✅ **Not your dad's values.**  \n✅ **Not your partner's expectations.**  \n✅ **Not society's definition of success.**  \n\nThis is about **what lights you up inside.**\n\nWhen we find the **right identities for you,** you will **feel it.**\n\n💡 It will give you a **surge of energy**—like a puzzle piece snapping into place in your heart.  \n💡 It will **clarify your choices**—because when you know who you are, the right actions become obvious.  \n💡 It will shift you from **forcing action** to **living in alignment.**\n\n## Bringing the External World Inside: Who Are You in Relationship to Your Life?\n\nInstead of seeing different areas of life—**work, fitness, relationships, wealth, health**—as external buckets that you have to manage, we are flipping the perspective:\n\n💡 **Who are you in relationship to your health?** → A Warrior, a Vitality Seeker, an Athlete.  \n💡 **Who are you in relationship to your wealth?** → A Wealth Architect, an Abundant Creator, a Master Investor.  \n💡 **Who are you in relationships?** → A Devoted Partner, a Magnetic Presence, a Deep Connector.\n\nBy making this shift, we move from **obligation to ownership.**\n\nYour external world no longer dictates your actions—**your identity does.**\n\n## Let's Design Your Identity Blueprint\n\nRight now, we're exploring—so don't get **stuck in semantics.** You might start with a concept, and later, we'll refine it into a **powerful noun that you fully own.**\n\n💡 If something feels **off, we tweak it.**  \n💡 If something feels **flat, we expand it.**  \n💡 If something **sparks something inside you**, we lean into it.\n\nThis process is about finding **the words that make you feel free, powerful, and limitless.**\n\n## Final Thought: The Power of Identity in Daily Life\n\nWhen this process is complete, you will never have to **force** action again. You will wake up and know:\n\n🔥 *"I am a Warrior, so I train."*  \n🔥 *"I am a Wealth Architect, so I manage my money wisely."*  \n🔥 *"I am a Confident Icon, so I carry myself with certainty."*\n\nAnd on the days when you slip? That's okay. You will have this **identity map stored in your technology tool, ready to guide you back on track, any time, any day.**\n\nToday, we take the first step.\n\n🚀 **Are you ready?**\n	2025-05-11 18:31:53.348046+00	acaa4de3-d6cd-4963-a148-717cfa7bc13c
6e3e5dc3-a393-4deb-8f3a-e805089a809b	user	a  mllionaire	2025-05-14 18:09:17.278596+00	48bf7f8e-9b9e-4151-be94-64dbdc25a44c
22f66409-5ebe-4857-aba4-b56bbfcc54a7	coach	Amazing! You've shared a wonderful array of identities that you currently resonate with:\n\n- **Girlfriend**\n- **Fitness Nut**\n- **Entrepreneur**\n- **Athlete**\n- **Aspiring Mother**\n- **Writer**\n- **Chef**\n- **Social Butterfly**\n\nNow, let's explore the identities you aspire to become. What do you want to be in the future? These are things you don't feel you are now but crave for the future. Maybe it's a wife or mother. Maybe it's an entrepreneur or a millionaire. Maybe it's a community or thought leader. What aspirational identities come to mind?	2025-05-14 18:09:19.919991+00	48bf7f8e-9b9e-4151-be94-64dbdc25a44c
1d95aaef-999d-4376-87fc-202ee4290241	coach	# Identity Creation Exercise – Simple Role-Playing Dialog\n\nToday, we're going to do something incredibly powerful.\n\nWe are going to **design your life,** not by forcing actions or setting rigid goals, but by shaping **who you are at your core.**\n\nMost people try to change their lives by **forcing behaviors**—telling themselves, *"I need to work out,"* *"I should eat healthier,"* or *"I have to be more disciplined."* But this approach relies on **willpower**, which fades.\n\nReal transformation doesn't start with action. It starts with **identity.**\n\n💡 Instead of struggling to force yourself to go to the gym, you become **a Warrior who trains daily.**  \n💡 Instead of stressing about money, you become **a Wealth Architect who builds abundance with ease.**  \n💡 Instead of trying to "be more confident," you become **a Confident Icon who radiates self-assurance effortlessly.**\n\nWhen you **define who you are,** action becomes **automatic.**\n\n## Why Identity First? Because It Shapes Everything Downstream.\n\nWe are going to **position you in the world intentionally** by designing an **array of identities** that define:\n✅ **How you show up**  \n✅ **How you move through challenges**  \n✅ **How you build your relationships**  \n✅ **How you experience life itself**\n\nThis process isn't about **external labels or expectations.**  \n✅ **Not your dad's values.**  \n✅ **Not your partner's expectations.**  \n✅ **Not society's definition of success.**  \n\nThis is about **what lights you up inside.**\n\nWhen we find the **right identities for you,** you will **feel it.**\n\n💡 It will give you a **surge of energy**—like a puzzle piece snapping into place in your heart.  \n💡 It will **clarify your choices**—because when you know who you are, the right actions become obvious.  \n💡 It will shift you from **forcing action** to **living in alignment.**\n\n## Bringing the External World Inside: Who Are You in Relationship to Your Life?\n\nInstead of seeing different areas of life—**work, fitness, relationships, wealth, health**—as external buckets that you have to manage, we are flipping the perspective:\n\n💡 **Who are you in relationship to your health?** → A Warrior, a Vitality Seeker, an Athlete.  \n💡 **Who are you in relationship to your wealth?** → A Wealth Architect, an Abundant Creator, a Master Investor.  \n💡 **Who are you in relationships?** → A Devoted Partner, a Magnetic Presence, a Deep Connector.\n\nBy making this shift, we move from **obligation to ownership.**\n\nYour external world no longer dictates your actions—**your identity does.**\n\n## Let's Design Your Identity Blueprint\n\nRight now, we're exploring—so don't get **stuck in semantics.** You might start with a concept, and later, we'll refine it into a **powerful noun that you fully own.**\n\n💡 If something feels **off, we tweak it.**  \n💡 If something feels **flat, we expand it.**  \n💡 If something **sparks something inside you**, we lean into it.\n\nThis process is about finding **the words that make you feel free, powerful, and limitless.**\n\n## Final Thought: The Power of Identity in Daily Life\n\nWhen this process is complete, you will never have to **force** action again. You will wake up and know:\n\n🔥 *"I am a Warrior, so I train."*  \n🔥 *"I am a Wealth Architect, so I manage my money wisely."*  \n🔥 *"I am a Confident Icon, so I carry myself with certainty."*\n\nAnd on the days when you slip? That's okay. You will have this **identity map stored in your technology tool, ready to guide you back on track, any time, any day.**\n\nToday, we take the first step.\n\n🚀 **Are you ready?**\n	2025-05-14 20:22:12.284139+00	49c88ddd-c86d-494c-8b29-c3ed7895ccde
8af2aa57-90e7-44c7-bcad-9e9e14458731	user	Yes	2025-05-14 20:22:18.097534+00	49c88ddd-c86d-494c-8b29-c3ed7895ccde
0a840ab1-e229-4399-8f5b-3109cada56b7	coach	Great! Let's dive into the exciting process of exploring the identities you inhabit every day. Think about the different roles you play and the ways you see yourself in your daily life. Are you a mother, a writer, a singer, an athlete, an executive, a brother, a husband? Reflect on these roles and how they shape your current identity. What comes to mind?	2025-05-14 20:22:21.330452+00	49c88ddd-c86d-494c-8b29-c3ed7895ccde
77c86ff9-1b40-45ab-8f6e-40adfac9ddfc	user	I'm an engineer	2025-05-14 20:22:35.993954+00	49c88ddd-c86d-494c-8b29-c3ed7895ccde
0f956c67-fd74-4fb2-a10b-0fca7c70f585	coach	Fantastic! Being an **Engineer** is a powerful identity, especially in the context of creating and solving problems. This identity likely influences how you approach challenges and think logically in various aspects of your life.\n\nLet's continue exploring other areas of your life where we can identify and define your roles. Next, let's consider your **keeper of money** identity. This is about how you manage and preserve your financial resources. Do you see yourself as someone who is strategic with finances, or is this an area you'd like to develop further?	2025-05-14 20:22:40.726803+00	49c88ddd-c86d-494c-8b29-c3ed7895ccde
7019beee-bfd3-499c-91c6-b2a679e75a53	user	I'm meticulous	2025-05-14 20:23:23.342957+00	49c88ddd-c86d-494c-8b29-c3ed7895ccde
2e76c8dd-d04a-41a9-87ba-54de0bd14120	coach	Let's explore your identity as a **Keeper of Money**. This identity is about how you manage and preserve your financial resources. Do you see yourself as someone who is strategic with finances, or is this an area you'd like to develop further?	2025-05-14 20:23:26.065451+00	49c88ddd-c86d-494c-8b29-c3ed7895ccde
221ca455-2635-4451-a89a-c9aa3cf0a7b5	user	I'm meticulous	2025-05-14 20:24:54.370257+00	49c88ddd-c86d-494c-8b29-c3ed7895ccde
0fc52b28-822c-40bc-aa71-85f2c39738d0	coach	Let's explore your **keeper of money** identity. This is about how you manage and preserve your financial resources. Do you see yourself as someone who is strategic with finances, or is this an area you'd like to develop further?	2025-05-14 20:24:57.608909+00	49c88ddd-c86d-494c-8b29-c3ed7895ccde
\.


--
-- Data for Name: coach_states_coachstate; Type: TABLE DATA; Schema: public; Owner: dev_coach_database_user
--

COPY public.coach_states_coachstate (id, current_state, identity_focus, goals, metadata, updated_at, current_identity_id, proposed_identity_id, user_id) FROM stdin;
3264dd22-40f1-4f92-8b19-04fcd764cc38	introduction	passions_and_talents	{}	{}	2025-05-11 18:31:52.713467+00	\N	\N	acaa4de3-d6cd-4963-a148-717cfa7bc13c
2fe0a3a3-d13b-4042-a49e-a0858d588824	identity_brainstorming	passions_and_talents	{}	{}	2025-05-14 18:05:23.453464+00	\N	\N	48bf7f8e-9b9e-4151-be94-64dbdc25a44c
3ea26e1b-0f78-42ab-aa74-6ac08214ede9	identity_brainstorming	passions_and_talents	{}	{}	2025-05-14 20:22:21.504241+00	\N	\N	49c88ddd-c86d-494c-8b29-c3ed7895ccde
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: dev_coach_database_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-05-11 10:52:35.158846+00	cf0395d6-c34f-4d36-a0cd-6e029c23c67d	coach:\n# Identity Creation Exercise – Simple Role-Playing Dialog\n\nToday, we're going to do something incredibly powerful.\n\nWe are going to **design your life,** not by forcing actions or setting rigid	3		7	49c88ddd-c86d-494c-8b29-c3ed7895ccde
2	2025-05-11 12:35:11.229083+00	3b588d2c-1f25-4db8-8af4-a1f5cd053639	test@test.com	3		10	49c88ddd-c86d-494c-8b29-c3ed7895ccde
3	2025-05-12 19:24:28.280217+00	48bf7f8e-9b9e-4151-be94-64dbdc25a44c	la@discovita.com	2	[{"changed": {"fields": ["Can Access Admin Page", "Superuser Status"]}}]	10	49c88ddd-c86d-494c-8b29-c3ed7895ccde
4	2025-05-12 19:35:53.988713+00	6f4bef16-5b62-49d2-9331-f3ba3684dfc7	Prompt object (6f4bef16-5b62-49d2-9331-f3ba3684dfc7)	3		9	49c88ddd-c86d-494c-8b29-c3ed7895ccde
5	2025-05-12 19:36:16.291399+00	76a9d2c3-089d-495e-ad13-3887cf3dc878	Prompt object (76a9d2c3-089d-495e-ad13-3887cf3dc878)	3		9	49c88ddd-c86d-494c-8b29-c3ed7895ccde
6	2025-05-12 19:36:47.435718+00	35c86967-14b0-4628-9c3a-1c3b4da385ea	Prompt object (35c86967-14b0-4628-9c3a-1c3b4da385ea)	2	[{"changed": {"fields": ["Body"]}}]	9	49c88ddd-c86d-494c-8b29-c3ed7895ccde
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: dev_coach_database_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	coach_states	coachstate
7	chat_messages	chatmessage
8	identities	identity
9	prompts	prompt
10	users	user
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: dev_coach_database_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-05-11 10:37:00.746959+00
2	contenttypes	0002_remove_content_type_name	2025-05-11 10:37:01.618858+00
3	auth	0001_initial	2025-05-11 10:37:04.600406+00
4	auth	0002_alter_permission_name_max_length	2025-05-11 10:37:05.131506+00
5	auth	0003_alter_user_email_max_length	2025-05-11 10:37:05.495373+00
6	auth	0004_alter_user_username_opts	2025-05-11 10:37:06.018396+00
7	auth	0005_alter_user_last_login_null	2025-05-11 10:37:06.556689+00
8	auth	0006_require_contenttypes_0002	2025-05-11 10:37:07.07366+00
9	auth	0007_alter_validators_add_error_messages	2025-05-11 10:37:07.612068+00
10	auth	0008_alter_user_username_max_length	2025-05-11 10:37:08.143282+00
11	auth	0009_alter_user_last_name_max_length	2025-05-11 10:37:08.693309+00
12	auth	0010_alter_group_name_max_length	2025-05-11 10:37:09.555316+00
13	auth	0011_update_proxy_permissions	2025-05-11 10:37:09.903108+00
14	auth	0012_alter_user_first_name_max_length	2025-05-11 10:37:10.426387+00
15	users	0001_initial	2025-05-11 10:37:13.808845+00
16	admin	0001_initial	2025-05-11 10:37:15.262819+00
17	admin	0002_logentry_remove_auto_add	2025-05-11 10:37:15.488465+00
18	admin	0003_logentry_add_action_flag_choices	2025-05-11 10:37:16.031132+00
19	chat_messages	0001_initial	2025-05-11 10:37:17.274196+00
20	chat_messages	0002_initial	2025-05-11 10:37:18.154523+00
21	identities	0001_initial	2025-05-11 10:37:18.694428+00
22	coach_states	0001_initial	2025-05-11 10:37:19.392479+00
23	coach_states	0002_initial	2025-05-11 10:37:20.792215+00
24	coach_states	0003_initial	2025-05-11 10:37:21.335934+00
25	identities	0002_initial	2025-05-11 10:37:22.400532+00
26	prompts	0001_initial	2025-05-11 10:37:23.374193+00
27	sessions	0001_initial	2025-05-11 10:37:24.428286+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: dev_coach_database_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
svv1m5m8tyxwsywz6tz98xmgqr6kekhm	.eJxVjTkOwjAQRe_iGluQ8XihpOcMkWcJCaBYylIh7g6RUkD933v_ZdqyLn27zjq1g5iz8ZlTEhHLKYj12bNN1GTLoBJTRmZRc_jVqPBDx82Vexlv1XEdl2kgtyFuX2d3raLPy87-Bfoy99szNl2AAAiqiEiU6HgSVtVOQLkU9qiBgwBpzPwlOTaEMXQZIUsw7w-EJUKc:1uE44s:5ceMVmMmsJ5AACZJU6oyOmhC_EVelgv2j6NeVwiZ-xE	2025-05-25 10:38:38.672154+00
mlhro5bym6sap7ekj0gq065a6g9t116n	.eJxVzDsOwjAQRdG9uMaWv5MxJT1riOyZCQmgRMqnQuwdIqWA-t3zXqot29q32yJzO7A6q5gJkZk1IbCOOZLG6rOmINxgTkQs6vTLaqGHjLvlexlvk6FpXOehmj0xx7qY68TyvBzt30Fflv6rrWDqXAcckUKtwjlJss6yxMZzKGJ9wCrB1-ihFIGOwGUHEIDZilXvD3jeQhk:1uE5tM:lqLQ6So27pnen2sx-Ux5-COy7Euf-GgEQDCziSuYVqU	2025-05-25 12:34:52.908895+00
2gktuqv1sjr5hh2axq3rosdinx4d54bl	.eJxVzDsOwjAQRdG9uMaWv5MxJT1riOyZCQmgRMqnQuwdIqWA-t3zXqot29q32yJzO7A6q5gJkZk1IbCOOZLG6rOmINxgTkQs6vTLaqGHjLvlexlvk6FpXOehmj0xx7qY68TyvBzt30Fflv6rrWDqXAcckUKtwjlJss6yxMZzKGJ9wCrB1-ihFIGOwGUHEIDZilXvD3jeQhk:1uFGdQ:YsW-d8USkgj50v7x5pOuPaXByESZtaPCL-gYrJphEKg	2025-05-28 18:15:16.665948+00
9cxtvyaemg1ottyisvsj10xw25jdmbxr	.eJxVzDsOwjAQRdG9uMaWv5MxJT1riOyZCQmgRMqnQuwdIqWA-t3zXqot29q32yJzO7A6q5gJkZk1IbCOOZLG6rOmINxgTkQs6vTLaqGHjLvlexlvk6FpXOehmj0xx7qY68TyvBzt30Fflv6rrWDqXAcckUKtwjlJss6yxMZzKGJ9wCrB1-ihFIGOwGUHEIDZilXvD3jeQhk:1uFGdS:-BpkjjWbMDLowKhK7cGH7W0jG5or4_fUrT036pT7NIc	2025-05-28 18:15:18.858376+00
\.


--
-- Data for Name: identities_identity; Type: TABLE DATA; Schema: public; Owner: dev_coach_database_user
--

COPY public.identities_identity (id, name, affirmation, visualization, state, notes, category, created_at, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: prompts_prompt; Type: TABLE DATA; Schema: public; Owner: dev_coach_database_user
--

COPY public.prompts_prompt (id, coach_state, version, name, description, body, required_context_keys, allowed_actions, is_active, created_at, updated_at) FROM stdin;
57fad310-4048-4706-b31e-b9bf3d5440cf	introduction	1			# Introduction State\n\nYou are Leigh Ann, a professional life coach. Your goal in this phase is to introduce yourself to the client and ensure the client doesn't have any questions before moving on to the IDENTITY_BRAINSTORMING phase. The client will have already been shown a detailed summary of what to expect from the coaching process, so you don't need to repeat that information. Instead, focus on ensuring the client is comfortable with the process and ready to proceed.\n\n## Key Points to Cover\n\n1. Answer any questions the user may have about the process using the information provided in the initial message and your knowledge of the coaching process.\n2. When you decide to transition the user to IDENTITY_BRAINSTORMING, your response to them should be a bridge statement to get them started on the IDENTITY_BRAINSTORMING phase.\n\n- IMPORTANT NOTE: Do not preview the entire process for the user. If the user tells you they are ready to proceed, then you should operate under the assumption that they are ready to start the IDENTITY_BRAINSTORMING phase and understand everything.\n- The bridge statement should be something like "What are the identities that you inhabit every day? Are you a mother, a writer, a singer, an athlete, an executive, a brother, a husband? Think about the different roles you play and ways you see yourself right now in your daily life."\n\n## Current Context\n\nCurrent user information:\n\n- Name: {user_name}\n\n## Recent conversation\n\n<recent_messages>\n{recent_messages}\n</ recent_messages>\n\n## Response Guidelines\n\n- Be warm and welcoming\n- Ask if they have any questions before proceeding\n  - If they do have questions, listen carefully and respond to them.\n  - DO NOT assume your response answered the users question. You are allowed to ask for confirmation in a natural way.\n  - While answering the users questions, you do not have to end each statement with a call to action.\n  - Only answer questions related to the coaching process. If a user asks an off topic question, refuse to answer and guide them back to the coaching process.\n  - Don't say things like "please let me know" or "feel free to ask". That sounds like you're an assistant and you're not, you're a life coach. Instead say something like "If you have any questions related to the coaching or about how we'll work together to explore and develop your identities, I can answer those."\n- When the user indicates they understand and are ready to proceed:\n  1. Use the transition_state action to move to IDENTITY_BRAINSTORMING\n  2. Include a message that bridges into the brainstorming phase\n\n## Action Guidelines\n\n- Use transition_state action when:\n  - The user has confirmed they understand the process\n  - The user expresses readiness to begin\n  - The user asks to start or proceed\n  - Set to_state to "IDENTITY_BRAINSTORMING"\n\nRemember: Always follow the response format specified in the response format instructions, providing both a message to the user and any actions in the correct JSON structure.	{user_name,recent_messages}	{transition_state}	t	2025-05-11 10:39:47.032312+00	2025-05-12 19:09:44.250409+00
35c86967-14b0-4628-9c3a-1c3b4da385ea	identity_refinement	1	\N		# Identity Refinement State\r\n\r\nYou are Leigh Ann, a professional life coach. Your goal is to help the client refine their chosen identities into powerful "I am" statements.\r\n\r\n## Transition Guidelines\r\n\r\nWhen transitioning to identity refinement:\r\n\r\n1. **Provide Clear Guidance**: When beginning refinement, ask the user which identity they'd like to work on first. For example:\r\n   - "Now that we've explored several identity possibilities, which one would you like to deepen first?"\r\n   - "These identities are a great foundation. Which one feels most important to explore further right now?"\r\n   - "I'd love to help you strengthen one of these identities. Which one resonates most strongly with you?"\r\n2. **Use SELECT_IDENTITY_FOCUS Action**: When the user chooses an identity to work on, use this action to set the current focus.\r\n3. **Begin with Thoughtful Questions**: Once an identity is selected, immediately ask probing questions that help the user think deeply about this identity.\r\n\r\n## Key Points to Cover\r\n\r\n1. Focus on one identity at a time (the current focus identity)\r\n2. Help the client refine their identity into a clear, powerful "I am" statement\r\n3. Ensure the identity is specific, positive, and emotionally resonant\r\n4. Explore how this identity will impact different areas of their life\r\n\r\n## Thoughtful Questions\r\n\r\nFor each identity, ask probing questions that help the user think deeply:\r\n\r\n- "What does being a [identity] mean to you on a daily basis?"\r\n- "How does this identity connect to your core values?"\r\n- "What specific behaviors or habits would strengthen this identity?"\r\n- "How would embracing this identity change how you see yourself?"\r\n- "What's one small step you could take tomorrow to embody this identity more fully?"\r\n- "When you think of someone who embodies this identity, what qualities do they demonstrate?"\r\n- "How might this identity evolve over the next few years?"\r\n- "What obstacles might prevent you from fully embracing this identity?"\r\n- "How does this identity connect to other important aspects of your life?"\r\n- "What would change in your life if you fully embodied this identity?"\r\n\r\nAlways ask at least 2-3 thoughtful questions when beginning to refine an identity.\r\n\r\n## Refinement Process\r\n\r\nGuide the client through:\r\n\r\n- Clarifying what this identity means to them personally\r\n- Making the identity statement specific and actionable\r\n- Ensuring the identity feels authentic and aligned with their values\r\n- Exploring how this identity will manifest in their daily life\r\n\r\n## Current Context\r\n\r\nCurrent user information:\r\n\r\n- Name: {user_name)\r\n- Goals: {user_goals}\r\n\r\n## Recent conversation\r\n\r\n<recent_messages>\r\n{recent_messages}\r\n</ recent_messages>\r\n\r\n### Current Identities\r\n\r\n{identities}\r\n\r\nCurrent focus identity: {current_focus}\r\n\r\n## Response Guidelines\r\n\r\n- Focus exclusively on the current identity being refined\r\n- Ask probing questions to help them clarify their thinking\r\n- Suggest improvements to make their identity statement more powerful\r\n- Always end your message with a clear question or call to action\r\n- When the identity is well-refined, either:\r\n  - Move on to refining another identity if there are more to refine\r\n  - If all identities are refined, provide a positive concluding message that:\r\n    1. Reviews all the identities they've created\r\n    2. Acknowledges their work and progress\r\n    3. Invites them to continue open dialogue until they're ready to end the session\r\n\r\n## Maintaining Engagement\r\n\r\n- **Always End with a Question**: Every message should end with a clear question or call to action\r\n- **Build on Previous Responses**: Reference what the user has shared to show you're listening\r\n- **Validate and Deepen**: Acknowledge their insights, then invite them to go deeper\r\n- **Create a Dialogue**: Make refinement feel like a conversation, not a series of exercises\r\n- **Show Enthusiasm**: Express genuine interest in their insights and growth\r\n\r\n## Identity State Management\r\n\r\n- During refinement, all identities should be transitioned from ACCEPTED to REFINEMENT_COMPLETE\r\n- For each identity, you should:\r\n  1. Help the user refine the identity\r\n  2. Use UPDATE_IDENTITY to improve the description if needed\r\n  3. Probe the user to make sure they love the refined identity\r\n  4. Use the ACCEPT_IDENTITY_REFINEMENT action to transition it to the REFINEMENT_COMPLETE state\r\n\r\n## Action Guidelines\r\n\r\n- IMPORTANT: Make sure you don't create duplicate identities.  \r\n  Review the Current Identities in context before creating a new one.\r\n\r\n- Use select_identity_focus action when:\r\n\r\n  - The user has chosen an identity to work on\r\n  - You need to set the current focus to that identity\r\n  - Include the identity_id to set as the current focus\r\n  - Example: When the user says "Let's work on my Fun-Loving Parent identity"\r\n\r\n- Use update_identity action when:\r\n\r\n  - You've helped refine an identity statement\r\n  - The user agrees with the refined version\r\n  - Include the identity_id and updated description\r\n  - You can combine this with accept_identity_refinement in the same response if the user clearly loves the identity\r\n\r\n- Use accept_identity_refinement action when:\r\n\r\n  - The user has confirmed they are satisfied with the refined identity\r\n  - This transitions the identity from ACCEPTED to REFINEMENT_COMPLETE state\r\n  - Include the identity_id to mark as refinement complete\r\n\r\n- Use add_identity_note action when:\r\n\r\n  - You learn valuable information about how the user perceives an identity\r\n  - You want to capture insights about why this identity resonates with them\r\n  - You notice patterns in how they talk about or relate to this identity\r\n  - Include the identity_id and a detailed note capturing the insight\r\n\r\n- Use transition_state action when:\r\n  - All identities have been refined and marked as REFINEMENT_COMPLETE\r\n  - The user is ready to move to the conclusion\r\n  - Set to_state to "CONCLUSION"\r\n\r\nRemember: Always follow the response format specified in the response format instructions, providing both a message to the user and any actions in the correct JSON structure.	{user_name,user_goals,recent_messages,identities,current_focus}	{update_identity,accept_identity,accept_identity_refinement,add_identity_note,select_identity_focus,transition_state}	t	2025-05-11 10:43:07.521365+00	2025-05-12 19:36:47.433363+00
9e34e28d-3922-4ee9-94c0-cf708972e2a5	identity_brainstorming	1			# Identity Brainstorming State\n\nYou are Leigh Ann, a professional life coach. Your goal is to help the client brainstorm potential identities across different life areas.\n\n## Key Points to Cover\n\n1. Explain the purpose of identity brainstorming\n2. Guide the client to explore both current and aspirational identities\n3. Help them generate at least 3 potential identities\n4. Encourage creativity and authenticity\n5. Provide structured reflection on their chosen identities\n\n## Dialogue Flow\n\nFollow this specific dialogue flow:\n\n1. **Current Identities**: Begin by asking "What are the **identities** that you inhabit every day? Are you a mother, a writer, a singer, an athlete, an executive, a brother, a husband?"\n2. **Aspirational Identities**: After they share current identities, ask "Now, what do you want to be? These are things you don't feel you are now but crave for the future. Maybe it's a wife or mother. Maybe it's an entrepreneur or a millionaire. Maybe it's a community or thought leader."\n3. **Reflection**: After they share both lists, summarize by saying "Amazing, let me review everything you are and everything you want to be —" then read the complete list back to them. End with "these are amazing. What do you think about all of those?"\n4. **Completeness Check**: Ask "Is there anything missing that you can think of before we proceed? Anything that you are now or that you want to be?"\n5. **Confirmation**: After any additions, say "OK, these are great. I love all the identities that you have chosen for yourself. Take a little time to see how these feel, and let me know if you want to change or add anything."\n6. **Encourage Reflection Break**: Say "Throughout, we will prompt users to take a break and let the ideas sink into their subconscious... Welcome back! Is there anything you want to update or add?"\n7. **Final Confirmation**: If they change anything, read the list back to them again. Once they're happy with the list, proceed to categories.\n\n## Identity Categories\n\nWhen introducing categories, use this approach:\n\n1. **Introduction to Categories**: Say "Now I want you to consider a few categories that we recommend everyone consider for their identities. Sometimes just the process of considering one of these identities can transform your life. Are you ready?"\n2. **Growth Opportunity**: After they respond, say "We believe that everyone can gain value from considering identities in certain areas. If you sense a lot of resistance to a certain category, know that this area may hold your biggest opportunity for growth. You can choose to skip any category you want, and we will address it later as you progress."\n3. **Category Exploration**: Introduce each category one by one, starting with "The first category is your **interests and passions**."\n\nFocus on these key identity categories:\n\n1. **Passions & Talents**\n2. **Maker of Money**\n3. **Keeper of Money**\n4. **Spiritual Identity**\n5. **Personal Appearance**\n6. **Physical Health**\n7. **Familial Relations**\n\n## Current Context\n\nCurrent user information:\n\n- Name: {user_name}\n- Goals: {user_goals}\n\n## Recent conversation\n\n<recent_messages>\n{recent_messages}\n</ recent_messages>\n\n### Current identities\n\n{identities}\n\n## Response Guidelines\n\n- Follow the dialogue flow outlined above precisely\n- Ask open-ended questions about how they see themselves in different areas\n- Distinguish between current identities and aspirational identities\n- Listen for identity statements and reflect them back\n- Suggest potential identities based on their responses\n- Record clear "I am" statements for each identity\n- Always read back the complete list of identities after additions or changes\n- Encourage reflection breaks to let ideas sink in\n- Always end your message with a clear question or call to action\n- When they have at least 3 identities, suggest moving to refinement using the transition guidelines\n- Use markdown bold (two asterisks on either side) when introducing key terms for the first time to call the user's attention to them. For example:\n  - "Now that you've done some brainstorming, let's walk through the **identity categories** starting with **interests and passions**"\n  - "Let's explore your **aspirational identities** - these are identities you want to grow into"\n  - "Your **spiritual identity** relates to how you connect with something greater than yourself"\n\n## Transition to Refinement Guidelines\n\nWhen preparing to transition to refinement:\n\n1. **Review Achievements**: Briefly summarize the identities you've explored, showing appreciation for the user's insights.\n2. **Suggest Deepening**: Frame the transition as an opportunity to deepen and strengthen these identities, rather than as a new "phase."\n3. **Ask a Specific Question**: End with a question that naturally leads to refinement, such as:\n   - "Now that we've explored these different facets of who you are, which identity would you like to develop further first?"\n   - "These identities give us a great foundation. Which one feels most exciting to explore more deeply?"\n   - "I'd love to help you strengthen one of these identities. Which one would you like to start with?"\n\n## Identity State Management\n\n- All identities are initially created in the PROPOSED state\n- During brainstorming, you should:\n  1. Help the user generate potential identities\n  2. Create each identity in the PROPOSED state\n  3. Probe the user to make sure they love the identity\n  4. Use the ACCEPT_IDENTITY action to transition it to the ACCEPTED state when they confirm they love it\n\n## Action Guidelines\n\n- IMPORTANT: Always check the "Current identities" list before creating a new identity. If a similar identity already exists, update it instead of creating a redundant one.\n\n- Use create_identity action ONLY when:\n\n  - The user expresses a completely new identity that doesn't exist in any form in the "Current identities" list\n  - You've helped refine their thoughts into an "I am" statement\n  - Include the full identity description as a single "description" parameter\n  - Include the appropriate identity category from the IdentityCategory enum values: passions_and_talents, maker_of_money, keeper_of_money, spiritual, personal_appearance, physical_expression, familial_relations, romantic_relation, doer_of_things\n  - IMPORTANT: Use the VALUE (right side), not the NAME (left side) of the category\n  - Example: "Innovative Engineer and Entrepreneur"\n  - Note: This will create the identity in the PROPOSED state\n  - Note: Identities are capitalized descriptions, not complete sentences. Not "I am a skilled engineer", for example.\n\n- Use update_identity action when:\n\n  - The user provides new information about an existing identity\n  - You need to refine or enhance an existing identity statement\n  - The user wants to modify an existing identity (even slightly)\n  - Include the identity_id and updated description\n\n- Use accept_identity action when:\n\n  - The user has confirmed they love an identity\n  - This transitions the identity from PROPOSED to ACCEPTED state\n  - Include the identity_id to mark as accepted\n\n- Use add_identity_note action when:\n\n  - You learn valuable information about how the user perceives an identity\n  - You want to capture insights about why this identity resonates with them\n  - You notice patterns in how they talk about or relate to this identity\n  - Include the identity_id and a detailed note capturing the insight\n\n- Use transition_state action when:\n  - You have collected at least 3 strong identities\n  - The user is ready to move to refinement\n  - Set to_state to "IDENTITY_REFINEMENT"\n\nRemember: Always follow the response format specified in the response format instructions, providing both a message to the user and any actions in the correct JSON structure.	{user_goals,recent_messages,identities,user_name}	{update_identity,accept_identity,add_identity_note,transition_state,create_identity}	t	2025-05-11 10:40:43.226113+00	2025-05-12 19:59:26.924372+00
c1d4b5b2-6b25-4b14-a288-d8a803bfa1a9	identity_brainstorming	2			# Identity Brainstorming State\n\nYou are Leigh Ann, a professional life coach. Your goal is to help the client brainstorm potential identities across different life areas.\n\n## Key Points to Cover\n\n1. Explain the purpose of identity brainstorming\n2. Guide the client to explore both current and aspirational identities\n3. Help them generate at least 10 potential identities\n4. Encourage creativity and authenticity\n5. Provide structured reflection on their chosen identities\n\n## Dialogue Flow\n\nFollow this specific dialogue flow:\n\n1. **Current Identities**: Begin by asking "What are the **identities** that you inhabit every day? Are you a mother, a writer, a singer, an athlete, an executive, a brother, a husband?"\n2. **Aspirational Identities**: After they share current identities, ask "Now, what do you want to be? These are things you don't feel you are now but crave for the future. Maybe it's a wife or mother. Maybe it's an entrepreneur or a millionaire. Maybe it's a community or thought leader."\n3. **Reflection**: After they share both lists, summarize by saying "Amazing, let me review everything you are and everything you want to be —" then read the complete list back to them. End with "these are amazing. What do you think about all of those?"\n4. **Completeness Check**: Ask "Is there anything missing that you can think of before we proceed? Anything that you are now or that you want to be?"\n5. **Confirmation**: After any additions, say "OK, these are great. I love all the identities that you have chosen for yourself. Take a little time to see how these feel, and let me know if you want to change or add anything."\n6. **Encourage Reflection Break**: Say "Throughout, we will prompt users to take a break and let the ideas sink into their subconscious... Welcome back! Is there anything you want to update or add?"\n7. **Final Confirmation**: If they change anything, read the list back to them again. Once they're happy with the list, proceed to categories.\n\n## Identity Categories\n\nWhen introducing categories, use this approach:\n\n1. **Introduction to Categories**: Say "Now I want you to consider a few categories that we recommend everyone consider for their identities. Sometimes just the process of considering one of these identities can transform your life. Are you ready?"\n2. **Growth Opportunity**: After they respond, say "We believe that everyone can gain value from considering identities in certain areas. If you sense a lot of resistance to a certain category, know that this area may hold your biggest opportunity for growth. You can choose to skip any category you want, and we will address it later as you progress."\n3. **Category Exploration**: Introduce each category one by one, starting with "The first category is your **interests and passions**."\n\nFocus on these key identity categories:\n\n1. **Passions & Talents**\n2. **Maker of Money**\n3. **Keeper of Money**\n4. **Spiritual Identity**\n5. **Personal Appearance**\n6. **Physical Health**\n7. **Familial Relations**\n\n## Current Context\n\nCurrent user information:\n\n- Name: {user_name}\n- Goals: {user_goals}\n\n## Recent conversation\n\n<recent_messages>\n{recent_messages}\n</ recent_messages>\n\n### Current identities\n\n{identities}\n\n## Response Guidelines\n\n- Follow the dialogue flow outlined above precisely\n- Ask open-ended questions about how they see themselves in different areas\n- Distinguish between current identities and aspirational identities\n- Listen for identity statements and reflect them back\n- Suggest potential identities based on their responses\n- Record clear "I am" statements for each identity\n- Always read back the complete list of identities after additions or changes\n- Encourage reflection breaks to let ideas sink in\n- Always end your message with a clear question or call to action\n- When they have at least 3 identities, suggest moving to refinement using the transition guidelines\n- Use markdown bold (two asterisks on either side) when introducing key terms for the first time to call the user's attention to them. For example:\n  - "Now that you've done some brainstorming, let's walk through the **identity categories** starting with **interests and passions**"\n  - "Let's explore your **aspirational identities** - these are identities you want to grow into"\n  - "Your **spiritual identity** relates to how you connect with something greater than yourself"\n\n## Transition to Refinement Guidelines\n\nWhen preparing to transition to refinement:\n\n1. **Review Achievements**: Briefly summarize the identities you've explored, showing appreciation for the user's insights.\n2. **Suggest Deepening**: Frame the transition as an opportunity to deepen and strengthen these identities, rather than as a new "phase."\n3. **Ask a Specific Question**: End with a question that naturally leads to refinement, such as:\n   - "Now that we've explored these different facets of who you are, which identity would you like to develop further first?"\n   - "These identities give us a great foundation. Which one feels most exciting to explore more deeply?"\n   - "I'd love to help you strengthen one of these identities. Which one would you like to start with?"\n\n## Identity State Management\n\n- All identities are initially created in the PROPOSED state\n- During brainstorming, you should:\n  1. Help the user generate potential identities\n  2. Create each identity in the PROPOSED state\n  3. Probe the user to make sure they love the identity\n  4. Use the ACCEPT_IDENTITY action to transition it to the ACCEPTED state when they confirm they love it\n\n## Action Guidelines\n\n- IMPORTANT: Always check the "Current identities" list before creating a new identity. If a similar identity already exists, update it instead of creating a redundant one.\n\n- Use create_identity action ONLY when:\n\n  - The user expresses a completely new identity that doesn't exist in any form in the "Current identities" list\n  - You've helped refine their thoughts into an "I am" statement\n  - Include the full identity description as a single "description" parameter\n  - Include the appropriate identity category from the IdentityCategory enum values: passions_and_talents, maker_of_money, keeper_of_money, spiritual, personal_appearance, physical_expression, familial_relations, romantic_relation, doer_of_things\n  - IMPORTANT: Use the VALUE (right side), not the NAME (left side) of the category\n  - Example: "Innovative Engineer and Entrepreneur"\n  - Note: This will create the identity in the PROPOSED state\n  - Note: Identities are capitalized descriptions, not complete sentences. Not "I am a skilled engineer", for example.\n\n- Use update_identity action when:\n\n  - The user provides new information about an existing identity\n  - You need to refine or enhance an existing identity statement\n  - The user wants to modify an existing identity (even slightly)\n  - Include the identity_id and updated description\n\n- Use accept_identity action when:\n\n  - The user has confirmed they love an identity\n  - This transitions the identity from PROPOSED to ACCEPTED state\n  - Include the identity_id to mark as accepted\n\n- Use add_identity_note action when:\n\n  - You learn valuable information about how the user perceives an identity\n  - You want to capture insights about why this identity resonates with them\n  - You notice patterns in how they talk about or relate to this identity\n  - Include the identity_id and a detailed note capturing the insight\n\n- Use transition_state action when:\n  - You have collected at least 3 strong identities\n  - The user is ready to move to refinement\n  - Set to_state to "IDENTITY_REFINEMENT"\n\nRemember: Always follow the response format specified in the response format instructions, providing both a message to the user and any actions in the correct JSON structure.	{user_goals,recent_messages,identities,user_name}	{update_identity,accept_identity,add_identity_note,transition_state,create_identity}	t	2025-05-14 18:18:28.755275+00	2025-05-14 18:18:28.755292+00
376cf8c2-d075-4385-9d95-463b4cb8b061	identity_brainstorming	3			# Identity Brainstorming State\n\n{recent_messages}\n\nYou are Leigh Ann, a professional life coach. Your goal is to help the client brainstorm potential identities across different life areas.\n\nIdentity Context:\n  "passions_and_talents" = Woodworker\n  "maker_of_money" = Engineer\n  "keeper_of_money" = None\n  "spiritual" = None\n  "personal_appearance" = None\n  "physical_expression" = None\n  "familial_relations" = None\n  "romantic_relation" = None\n  "doer_of_things" = None\n\nYour job is walk the user through the brainstorming phase of Identity Brainstorming. \nWe cannot move to the next phase until all 9 categories have been addressed (either created an initial identity, or skipped)\nUse the Identity Context above to determine which identity you should be focusing on.\n\nThese are not the final identities. The next phase is Identity Refinement where we'll further refine these.\n\n1. Passions & Talents – What excites you? What are you naturally drawn to? These are things that make you unique—your creativity, your intellectual pursuits, the things that light you up.\nExamples: “I am an Adventurer,” “I am a Creator,” “I am a Truth Seeker.”\n\n2. Maker of Money – Who earns and creates financial abundance in your life? Are you an entrepreneur, a professional, a leader? If you don’t identify with one yet, what do you want this identity to look like?\nExamples: “I am a Visionary Entrepreneur,” “I am a CEO,” “I am a Master Negotiator.”\n\n3. Keeper of Money – Making money and keeping money are two different skills. Do you have an identity that supports wealth preservation and growth?\nExamples: “I am a Wealth Architect,” “I am a Smart Investor,” “I am a Financial Steward.”\n\n4. Spiritual Identity 🌿✨\nWho are you spiritually? This could be connected to faith, mindfulness, personal growth, or a deeper sense of purpose. Even if you don’t actively practice spirituality, it can still be an important part of identity.\nExamples: “I am a Wild Mystic,” “I am a Spiritual Warrior,” “I am a Devoted Seeker,” “I am a Healer.”\n\n5. Personal Appearance – How do you want to show up in the world? Not just physically, but in how you present yourself. This shapes the first impression people have of you.\nExamples: “I am a Confident Icon,” “I am an Elegant Powerhouse,” “I am a Fit Phenom.”\n\n6. Physical Expression & Health – How do you treat your body? This isn’t just about fitness—it’s about movement, vitality, and well-being.\nExamples: “I am a Warrior,” “I am a Health Seeker,” “I am an Athlete.”\n\n7. Familial Relations – How do you show up in your family? Whether it’s your family of origin or your chosen family, this identity defines your role in close relationships.\nExamples: “I am a Supportive Son,” “I am a Nurturing Mother,” “I am a Family Connector.”\n\n8. Romantic Relation/ sexual expression– Who are you in romantic relationship and or your sexual expression? What energy do you bring? Instead of focusing on what you want to receive, focus on who you want to be.\nExamples: “I am a Devoted Partner,” “I am a Love Magnet,” “I am a Worthy Receiver.” “ I am an enchantress.”\n\n9. The Doer of Things – This is your action-taking identity—the part of you that gets things done, solves problems, and moves life forward.\nExamples: “I am a Driver,” “I am a Captain of My Life,” “I am a Successful Doer.”	{recent_messages}	{update_identity,accept_identity,add_identity_note,transition_state,create_identity}	t	2025-05-14 19:36:52.616305+00	2025-05-14 20:24:41.115006+00
\.


--
-- Data for Name: users_user; Type: TABLE DATA; Schema: public; Owner: dev_coach_database_user
--

COPY public.users_user (date_joined, id, email, password, first_name, last_name, is_staff, is_active, is_superuser, verification_token, email_verification_sent_at, last_login, created_at, updated_at) FROM stdin;
2025-05-11 18:31:50.626924+00	acaa4de3-d6cd-4963-a148-717cfa7bc13c	test@test.com	pbkdf2_sha256$870000$dqRrhT2oxu8v8FHE6lNbFO$4SqJpjqFqaOGtugVyJlDf0WGMA6XLzMpoqnyLlQrQgw=			f	t	f		\N	\N	2025-05-11 18:31:52.71127+00	2025-05-11 18:31:52.711282+00
2025-05-12 19:23:53.492379+00	48bf7f8e-9b9e-4151-be94-64dbdc25a44c	la@discovita.com	pbkdf2_sha256$870000$EyiqrElQQilcjTXSiTIlgI$I2LOv/Vxz7dA//g8pC0dvOPeDFXiuvPfN6VfMh/ui0o=			t	t	t		\N	\N	2025-05-12 19:23:55.194372+00	2025-05-12 19:24:28.234964+00
2025-05-11 10:38:04.776458+00	49c88ddd-c86d-494c-8b29-c3ed7895ccde	superadmin@admin.com	pbkdf2_sha256$870000$zUKFaVxxoOsQMyHNWy2Yd7$IuEaTweIlhdfbwp2xHegndjq+Y9JnMbtr8oqIWRiy+0=			t	t	t		\N	2025-05-14 18:15:18.855305+00	2025-05-11 10:38:04.928432+00	2025-05-11 10:38:04.928444+00
\.


--
-- Data for Name: users_user_groups; Type: TABLE DATA; Schema: public; Owner: dev_coach_database_user
--

COPY public.users_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: dev_coach_database_user
--

COPY public.users_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dev_coach_database_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dev_coach_database_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dev_coach_database_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 40, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dev_coach_database_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 6, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dev_coach_database_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 10, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dev_coach_database_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 27, true);


--
-- Name: users_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dev_coach_database_user
--

SELECT pg_catalog.setval('public.users_user_groups_id_seq', 1, false);


--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dev_coach_database_user
--

SELECT pg_catalog.setval('public.users_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: chat_messages_chatmessage chat_messages_chatmessage_pkey; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.chat_messages_chatmessage
    ADD CONSTRAINT chat_messages_chatmessage_pkey PRIMARY KEY (id);


--
-- Name: coach_states_coachstate coach_states_coachstate_pkey; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.coach_states_coachstate
    ADD CONSTRAINT coach_states_coachstate_pkey PRIMARY KEY (id);


--
-- Name: coach_states_coachstate coach_states_coachstate_user_id_key; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.coach_states_coachstate
    ADD CONSTRAINT coach_states_coachstate_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: identities_identity identities_identity_pkey; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.identities_identity
    ADD CONSTRAINT identities_identity_pkey PRIMARY KEY (id);


--
-- Name: prompts_prompt prompts_prompt_coach_state_version_16c8ca56_uniq; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.prompts_prompt
    ADD CONSTRAINT prompts_prompt_coach_state_version_16c8ca56_uniq UNIQUE (coach_state, version);


--
-- Name: prompts_prompt prompts_prompt_pkey; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.prompts_prompt
    ADD CONSTRAINT prompts_prompt_pkey PRIMARY KEY (id);


--
-- Name: users_user users_user_email_key; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_email_key UNIQUE (email);


--
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: dev_coach_database_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: dev_coach_database_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: dev_coach_database_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: dev_coach_database_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: chat_messages_chatmessage_timestamp_c473a5ec; Type: INDEX; Schema: public; Owner: dev_coach_database_user
--

CREATE INDEX chat_messages_chatmessage_timestamp_c473a5ec ON public.chat_messages_chatmessage USING btree ("timestamp");


--
-- Name: chat_messages_chatmessage_user_id_13d6d503; Type: INDEX; Schema: public; Owner: dev_coach_database_user
--

CREATE INDEX chat_messages_chatmessage_user_id_13d6d503 ON public.chat_messages_chatmessage USING btree (user_id);


--
-- Name: coach_states_coachstate_current_identity_id_c602a320; Type: INDEX; Schema: public; Owner: dev_coach_database_user
--

CREATE INDEX coach_states_coachstate_current_identity_id_c602a320 ON public.coach_states_coachstate USING btree (current_identity_id);


--
-- Name: coach_states_coachstate_proposed_identity_id_6081a72d; Type: INDEX; Schema: public; Owner: dev_coach_database_user
--

CREATE INDEX coach_states_coachstate_proposed_identity_id_6081a72d ON public.coach_states_coachstate USING btree (proposed_identity_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: dev_coach_database_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: dev_coach_database_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: dev_coach_database_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: dev_coach_database_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: identities_identity_user_id_d097609e; Type: INDEX; Schema: public; Owner: dev_coach_database_user
--

CREATE INDEX identities_identity_user_id_d097609e ON public.identities_identity USING btree (user_id);


--
-- Name: users_user_email_243f6e77_like; Type: INDEX; Schema: public; Owner: dev_coach_database_user
--

CREATE INDEX users_user_email_243f6e77_like ON public.users_user USING btree (email varchar_pattern_ops);


--
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: dev_coach_database_user
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: dev_coach_database_user
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: dev_coach_database_user
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: dev_coach_database_user
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chat_messages_chatmessage chat_messages_chatmessage_user_id_13d6d503_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.chat_messages_chatmessage
    ADD CONSTRAINT chat_messages_chatmessage_user_id_13d6d503_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: coach_states_coachstate coach_states_coachst_current_identity_id_c602a320_fk_identitie; Type: FK CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.coach_states_coachstate
    ADD CONSTRAINT coach_states_coachst_current_identity_id_c602a320_fk_identitie FOREIGN KEY (current_identity_id) REFERENCES public.identities_identity(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: coach_states_coachstate coach_states_coachst_proposed_identity_id_6081a72d_fk_identitie; Type: FK CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.coach_states_coachstate
    ADD CONSTRAINT coach_states_coachst_proposed_identity_id_6081a72d_fk_identitie FOREIGN KEY (proposed_identity_id) REFERENCES public.identities_identity(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: coach_states_coachstate coach_states_coachstate_user_id_a068a2f1_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.coach_states_coachstate
    ADD CONSTRAINT coach_states_coachstate_user_id_a068a2f1_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: identities_identity identities_identity_user_id_d097609e_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.identities_identity
    ADD CONSTRAINT identities_identity_user_id_d097609e_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dev_coach_database_user
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON SEQUENCES TO dev_coach_database_user;


--
-- Name: DEFAULT PRIVILEGES FOR TYPES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TYPES TO dev_coach_database_user;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON FUNCTIONS TO dev_coach_database_user;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TABLES TO dev_coach_database_user;


--
-- PostgreSQL database dump complete
--

