# Generated by Django 5.1.3 on 2026-06-26 13:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.authentication.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this object.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address this invite was sent to (locked on register).",
                        max_length=254,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.authentication.models.generate_invite_token,
                        help_text="Magic-link token (secrets.token_hex(32)).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=apps.authentication.models.default_invite_expiry,
                        help_text="Invite is invalid after this time.",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When an account was created from this invite (null = pending).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who created this invite.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="authenticat_email_fd8ff6_idx")
                ],
            },
        ),
    ]
