# Generated by Django 5.1.3 on 2026-06-25 11:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identities", "0014_backfill_identity_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meditation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("GENERATING_PARTS", "Generating parts"),
                            ("READY_FOR_QC", "Ready for QC"),
                            ("ASSEMBLING", "Assembling"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                (
                    "final_video_s3_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="S3 key of the assembled final video (set in Phase 4 assembly)",
                        max_length=1024,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user this meditation is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meditations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MeditationSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order within the meditation (mirrors identity order)",
                    ),
                ),
                (
                    "current_video_prompt",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Editable prompt that seeds the next video generation",
                    ),
                ),
                (
                    "current_audio_script",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Editable narration script that seeds the next audio generation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identity",
                    models.ForeignKey(
                        help_text="The identity this segment is built from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meditation_segments",
                        to="identities.identity",
                    ),
                ),
                (
                    "meditation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="meditations.meditation",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MeditationAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("VIDEO", "Video"), ("AUDIO", "Audio")], max_length=16
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "s3_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="S3 key of the generated file (empty until generation completes)",
                        max_length=1024,
                    ),
                ),
                (
                    "prompt_snapshot",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The exact prompt/script that produced this version",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("GENERATING", "Generating"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Machine-readable error code if generation failed",
                        max_length=64,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="The chosen version for this (segment, kind)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="meditations.meditationsegment",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "version"],
            },
        ),
        migrations.AddConstraint(
            model_name="meditationsegment",
            constraint=models.UniqueConstraint(
                fields=("meditation", "identity"),
                name="unique_meditation_identity_segment",
            ),
        ),
        migrations.AddConstraint(
            model_name="meditationasset",
            constraint=models.UniqueConstraint(
                fields=("segment", "kind", "version"),
                name="unique_segment_kind_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="meditationasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("segment", "kind"),
                name="unique_active_asset_per_segment_kind",
            ),
        ),
    ]
