# Generated by Django 5.1.3 on 2025-06-17 08:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chat_messages", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this user note.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        help_text="A note about the user, extracted from chat."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this note was created.",
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        blank=True,
                        help_text="The chat message that prompted this note, if applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chat_messages.chatmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user this note belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
