# Generated by Django 5.1.5 on 2025-05-11 10:28

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this object.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "coach_state",
                    models.CharField(
                        choices=[
                            ("introduction", "Introduction"),
                            ("identity_brainstorming", "Identity Brainstorming"),
                            ("identity_refinement", "Identity Refinement"),
                        ],
                        help_text="The state of the coach this prompt is associated with.",
                        max_length=32,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="Version number of the prompt"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("body", models.TextField(help_text="Prompt body")),
                (
                    "required_context_keys",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("user_name", "User Name"),
                                ("user_goals", "User Goals"),
                                ("recent_messages", "Recent Messages"),
                                ("identities", "Identities"),
                                ("number_of_identities", "Number of Identities"),
                                (
                                    "current_identity_description",
                                    "Current Identity Description",
                                ),
                                ("current_focus", "Current Focus"),
                            ],
                            max_length=64,
                        ),
                        default=list,
                        help_text="List of required context keys for this prompt.",
                        size=None,
                    ),
                ),
                (
                    "allowed_actions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("create_identity", "Create Identity"),
                                ("update_identity", "Update Identity"),
                                ("accept_identity", "Accept Identity"),
                                (
                                    "accept_identity_refinement",
                                    "Accept Identity Refinement",
                                ),
                                ("add_identity_note", "Add Identity Note"),
                                ("transition_state", "Transition State"),
                                ("select_identity_focus", "Select Identity Focus"),
                            ],
                            max_length=64,
                        ),
                        default=list,
                        help_text="List of allowed action types for this prompt.",
                        size=None,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this prompt active?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("coach_state", "version")},
            },
        ),
    ]
