# Generated by Django 5.1.3 on 2025-05-15 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prompts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='coach_state',
            new_name='coaching_phase',
        ),
        migrations.AlterUniqueTogether(
            name='prompt',
            unique_together={('coaching_phase', 'version')},
        ),
    ]
