# Generated by Django 5.1.5 on 2025-05-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="required_context_keys",
            field=models.JSONField(
                default=list,
                help_text="List of required context keys for this prompt",
                verbose_name=models.CharField(
                    choices=[
                        ("user_name", "User Name"),
                        ("user_goals", "User Goals"),
                        ("user_summary", "User Summary"),
                        ("recent_messages", "Recent Messages"),
                        ("identities", "Identities"),
                        ("number_of_identities", "Number of Identities"),
                        (
                            "current_identity_description",
                            "Current Identity Description",
                        ),
                        ("identities_summary", "Identities Summary"),
                        ("phase", "Phase"),
                    ],
                    max_length=64,
                ),
            ),
        ),
    ]
