# Generated by Django 5.1.3 on 2025-05-15 11:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompts", "0002_rename_coach_state_to_coaching_phase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="allowed_actions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("create_identity", "Create Identity"),
                        ("update_identity", "Update Identity"),
                        ("accept_identity", "Accept Identity"),
                        ("accept_identity_refinement", "Accept Identity Refinement"),
                        ("add_identity_note", "Add Identity Note"),
                        ("transition_state", "Transition State"),
                        ("select_identity_focus", "Select Identity Focus"),
                    ],
                    max_length=64,
                ),
                blank=True,
                default=list,
                help_text="List of allowed action types for this prompt.",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="coaching_phase",
            field=models.CharField(
                choices=[
                    ("system_context", "System Context"),
                    ("introduction", "Introduction"),
                    ("identity_brainstorming", "Identity Brainstorming"),
                    ("identity_refinement", "Identity Refinement"),
                ],
                help_text="The phase of the coach this prompt is associated with.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="required_context_keys",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("user_name", "User Name"),
                        ("user_goals", "User Goals"),
                        ("recent_messages", "Recent Messages"),
                        ("identities", "Identities"),
                        ("number_of_identities", "Number of Identities"),
                        (
                            "current_identity_description",
                            "Current Identity Description",
                        ),
                        ("current_focus", "Current Focus"),
                    ],
                    max_length=64,
                ),
                blank=True,
                default=list,
                help_text="List of required context keys for this prompt.",
                size=None,
            ),
        ),
    ]
