# Generated by Django 5.1.3 on 2025-05-24 18:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompts", "0006_alter_prompt_allowed_actions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="coaching_phase",
            field=models.CharField(
                choices=[
                    ("system_context", "System Context"),
                    ("introduction", "Introduction"),
                    ("identity_warm_up", "Identity Warm-Up"),
                    ("identity_brainstorming", "Identity Brainstorming"),
                    ("identity_refinement", "Identity Refinement"),
                ],
                help_text="The phase of the coach this prompt is associated with.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="required_context_keys",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("user_name", "User Name"),
                        ("recent_messages", "Recent Messages"),
                        ("identities", "Identities"),
                        ("number_of_identities", "Number of Identities"),
                        ("identity_focus", "Identity Focus"),
                    ],
                    max_length=64,
                ),
                blank=True,
                default=list,
                help_text="List of required context keys for this prompt.",
                size=None,
            ),
        ),
    ]
