# Generated by Django 5.1.3 on 2025-12-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompts", "0016_alter_prompt_allowed_actions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="coaching_phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("system_context", "System Context"),
                    ("introduction", "Introduction"),
                    ("get_to_know_you", "Get to Know You"),
                    ("identity_warm_up", "Identity Warm-Up"),
                    ("identity_brainstorming", "Identity Brainstorming"),
                    ("brainstorming_review", "Brainstorming Review"),
                    ("identity_refinement", "Identity Refinement"),
                    ("anything_missing", "Anything Missing"),
                    ("identity_commitment", "Identity Commitment"),
                    ("i_am_statement", "I Am Statement"),
                    ("identity_visualization", "Identity Visualization"),
                ],
                help_text="The phase of the coach this prompt is associated with.",
                max_length=32,
                null=True,
            ),
        ),
    ]
