# Generated by Django 5.1.3 on 2026-01-03 23:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0017_alter_prompt_coaching_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='allowed_actions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('create_identity', 'Create Identity'), ('create_multiple_identities', 'Create Multiple Identities'), ('update_identity', 'Update Identity'), ('update_identity_name', 'Update Identity Name'), ('update_i_am_statement', 'Update I Am Statement'), ('update_identity_visualization', 'Update Identity Visualization'), ('accept_identity', 'Accept Identity'), ('accept_identity_refinement', 'Accept Identity Refinement'), ('accept_identity_commitment', 'Accept Identity Commitment'), ('accept_i_am_statement', 'Accept I Am Statement'), ('accept_identity_visualization', 'Accept Identity Visualization'), ('archive_identity', 'Archive Identity'), ('nest_identity', 'Nest Identity'), ('add_identity_note', 'Add Identity Note'), ('transition_phase', 'Transition Phase'), ('select_identity_focus', 'Select Identity Focus'), ('skip_identity_category', 'Skip Identity Category'), ('unskip_identity_category', 'Unskip Identity Category'), ('update_who_you_are', 'Update Who You Are'), ('update_who_you_want_to_be', 'Update Who You Want to Be'), ('update_asked_questions', 'Update Asked Questions'), ('set_current_identity', 'Set Current Identity'), ('combine_identities', 'Combine Identities'), ('add_user_note', 'Add User Note'), ('update_user_note', 'Update User Note'), ('delete_user_note', 'Delete User Note'), ('show_introduction_canned_response_component', 'Show Introduction Canned Response Component'), ('show_accept_i_am_component', 'Show Accept I Am Component'), ('show_suggest_i_am_statement_component', 'Show Suggest I Am Statement Component'), ('show_i_am_statements_summary_component', 'Show I Am Statements Summary Component'), ('show_combine_identities', 'Show Combine Identities'), ('show_nest_identities', 'Show Nest Identities'), ('show_archive_identity', 'Show Archive Identity'), ('persist_combine_identities', 'Persist Combine Identities'), ('persist_nest_identities', 'Persist Nest Identities'), ('persist_archive_identity', 'Persist Archive Identity'), ('persist_suggest_i_am_statement_component', 'Persist Suggest I Am Statement Component'), ('persist_i_am_statements_summary_component', 'Persist I Am Statements Summary Component')], max_length=64), blank=True, default=list, help_text='List of allowed action types for this prompt.', size=None),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_type',
            field=models.CharField(choices=[('coach', 'Coach'), ('sentinel', 'Sentinel'), ('system', 'System'), ('image_generation', 'Image Generation')], default='coach', help_text='Type of prompt (coach, sentinel, system, etc.)', max_length=32),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='required_context_keys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('user_name', 'User Name'), ('identities', 'Identities'), ('number_of_identities', 'Number of Identities'), ('identity_focus', 'Identity Focus'), ('who_you_are', 'Who You Are'), ('who_you_want_to_be', 'Who You Want to Be'), ('focused_identities', 'Focused Identities'), ('user_notes', 'User Notes'), ('current_message', 'Current Message'), ('previous_message', 'Previous Message'), ('current_phase', 'Current Phase'), ('brainstorming_category_context', 'Brainstorming Category Context'), ('current_identity', 'Current Identity'), ('asked_questions', 'Asked Questions'), ('refinement_identities', 'Refinement Identities'), ('commitment_identities', 'Commitment Identities'), ('i_am_identities', 'I Am Identities'), ('visualization_identities', 'Visualization Identities'), ('identity_ids', 'Identity IDs'), ('identity_for_image', 'Identity for Image')], max_length=64), blank=True, default=list, help_text='List of required context keys for this prompt.', size=None),
        ),
    ]
