# Generated by Django 5.1.3 on 2026-01-05 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prompts", "0018_alter_prompt_allowed_actions_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="prompt",
            unique_together={("prompt_type", "coaching_phase", "version")},
        ),
    ]
