# Generated by Django 5.1.3 on 2025-04-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_super_admin",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(
                default=False,
                help_text="This designation is used to separate students and parents from everyone else on the frontend.",
                verbose_name="Admin",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can access the admin site.",
                verbose_name="Can Access Admin Page",
            ),
        ),
    ]
