# Generated by Django 5.1.3 on 2025-07-05 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_scenario', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_scenario',
            field=models.ForeignKey(blank=True, help_text='Test scenario this user is associated with (for test data isolation).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_scenario.testscenario'),
        ),
    ]
