# Generated by Django 5.1.3 on 2025-05-03 13:44

import django.contrib.auth.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_is_super_admin_alter_user_is_admin_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this object.",
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
