# Generated by Django 5.1.3 on 2026-01-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_test_scenario"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age_range_visualization",
            field=models.CharField(
                blank=True,
                choices=[
                    ("twenties", "Young Adult (20s)"),
                    ("thirties", "In Their 30s"),
                    ("forties", "In Their 40s"),
                    ("fifties", "Middle-Aged (50s)"),
                    ("sixty_plus", "Mature (60+)"),
                ],
                help_text="How the user wants to be visualized (age)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="build_visualization",
            field=models.CharField(
                blank=True,
                choices=[
                    ("slim", "Slim"),
                    ("athletic", "Athletic"),
                    ("average", "Average"),
                    ("stocky", "Stocky"),
                    ("large", "Large"),
                ],
                help_text="How the user wants to be visualized (build)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="eye_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("brown", "Brown"),
                    ("blue", "Blue"),
                    ("green", "Green"),
                    ("hazel", "Hazel"),
                    ("gray", "Gray"),
                    ("amber", "Amber"),
                ],
                help_text="Preferred eye color for image generation",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender_visualization",
            field=models.CharField(
                blank=True,
                choices=[("man", "Man"), ("woman", "Woman"), ("person", "Person")],
                help_text="How the user wants to be visualized (gender)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="hair_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("black", "Black"),
                    ("brown", "Brown"),
                    ("blonde", "Blonde"),
                    ("red", "Red"),
                    ("auburn", "Auburn"),
                    ("gray", "Gray"),
                    ("white", "White"),
                    ("bald", "Bald"),
                ],
                help_text="Preferred hair color for image generation",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="height_visualization",
            field=models.CharField(
                blank=True,
                choices=[
                    ("short", "Short"),
                    ("below_average", "Below Average"),
                    ("average", "Average"),
                    ("above_average", "Above Average"),
                    ("tall", "Tall"),
                ],
                help_text="How the user wants to be visualized (height)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="skin_tone",
            field=models.CharField(
                blank=True,
                choices=[
                    ("light", "Light"),
                    ("medium_light", "Medium-Light"),
                    ("medium", "Medium"),
                    ("medium_dark", "Medium-Dark"),
                    ("dark", "Dark"),
                ],
                help_text="Preferred skin tone for image generation",
                max_length=20,
                null=True,
            ),
        ),
    ]
