# Generated by Django 5.1.5 on 2025-05-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can access the admin site. Also designates if the user is an admin on the site.",
                verbose_name="Can Access Admin Page",
            ),
        ),
    ]
