# Generated by Django 5.1.3 on 2026-01-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_age_range_visualization_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="age_range_visualization",
        ),
        migrations.RemoveField(
            model_name="user",
            name="build_visualization",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gender_visualization",
        ),
        migrations.RemoveField(
            model_name="user",
            name="height_visualization",
        ),
        migrations.AddField(
            model_name="user",
            name="age_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("twenties", "Young Adult (20s)"),
                    ("thirties", "In Their 30s"),
                    ("forties", "In Their 40s"),
                    ("fifties", "Middle-Aged (50s)"),
                    ("sixty_plus", "Mature (60+)"),
                ],
                help_text="Age range preference for image generation",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="build",
            field=models.CharField(
                blank=True,
                choices=[
                    ("slim", "Slim"),
                    ("athletic", "Athletic"),
                    ("average", "Average"),
                    ("stocky", "Stocky"),
                    ("large", "Large"),
                ],
                help_text="Build/body type preference for image generation",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("man", "Man"), ("woman", "Woman"), ("person", "Person")],
                help_text="Gender preference for image generation",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="height",
            field=models.CharField(
                blank=True,
                choices=[
                    ("short", "Short"),
                    ("below_average", "Below Average"),
                    ("average", "Average"),
                    ("above_average", "Above Average"),
                    ("tall", "Tall"),
                ],
                help_text="Height preference for image generation",
                max_length=20,
                null=True,
            ),
        ),
    ]
