# Generated by Django 5.1.3 on 2026-02-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_user_age_range_visualization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="build",
            field=models.CharField(
                blank=True,
                choices=[
                    ("slim", "Slim"),
                    ("athletic", "Athletic"),
                    ("average", "Average"),
                    ("stocky", "Stocky"),
                    ("large", "Large"),
                    ("muscular", "Muscular"),
                    ("petite", "Petite"),
                    ("curvy", "Curvy"),
                    ("full_figured", "Full-Figured"),
                    ("heavyset", "Heavyset"),
                ],
                help_text="Build/body type preference for image generation",
                max_length=20,
                null=True,
            ),
        ),
    ]
