# Generated by Django 5.1.5 on 2025-05-11 10:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this object.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("coach", "Coach"), ("user", "User")],
                        help_text="Role of the message sender (user or coach).",
                        max_length=32,
                    ),
                ),
                ("content", models.TextField(help_text="Content of the message.")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the message was sent.",
                    ),
                ),
            ],
        ),
    ]
