# Generated by Django 5.1.3 on 2025-10-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_messages", "0003_chatmessage_test_scenario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="component_config",
            field=models.JSONField(
                blank=True,
                help_text="Optional component configuration for persistent component rendering (stored as JSON).",
                null=True,
            ),
        ),
    ]
